In [5]:
import pandas as pd
import random
import re
import os
import json
from tqdm import tqdm
import hashlib

In [3]:
# list files in /Users/ataylor/Downloads/ch_metadata_agent/htan_data


directory = '/Users/ataylor/Downloads/ch_metadata_agent/htan_data'
files = [f for f in os.listdir(directory)]
print(len(files))

716

In [49]:
# check if any files have the same md5 checksum
md5_dict = {}
for file in files:
    if file.endswith('.md5'):
        with open(os.path.join(directory, file), 'r') as f:
            md5 = f.read().strip().split()[0]
            if md5 in md5_dict:
                md5_dict[md5].append(file)
            else:
                md5_dict[md5] = [file]

duplicates = {k: v for k, v in md5_dict.items() if len(v) > 1}
print(f"Found {len(duplicates)} duplicate files based on md5 checksum.")

Found 0 duplicate files based on md5 checksum.

In [50]:
# Check if any files have the same size
size_dict = {}
for file in files: 
    if not file.endswith('.md5'):
        size = os.path.getsize(os.path.join(directory, file))
        if size in size_dict:
            size_dict[size].append(file)
        else:
            size_dict[size] = [file]
duplicates_size = {k: v for k, v in size_dict.items() if len(v) > 1}
print(f"Found {len(duplicates_size)} duplicate files based on file size.")

Found 74 duplicate files based on file size.

In [51]:
# Check if any files have same content
import hashlib
content_dict = {}
for file in files:
    if not file.endswith('.md5'):
        with open(os.path.join(directory, file), 'rb') as f:
            content = f.read()
            content_hash = hashlib.md5(content).hexdigest()
            if content_hash in content_dict:
                content_dict[content_hash].append(file)
            else:
                content_dict[content_hash] = [file]
duplicates_content = {k: v for k, v in content_dict.items() if len(v) > 1}
print(f"Found {len(duplicates_content)} duplicate files based on file content.")

Found 51 duplicate files based on file content.

In [52]:
duplicates_content

{'55ec409683dbc1a4b0c8d384cee09de3': ['syn61375759.csv',
  'syn61375798.csv',
  'syn61375776.csv',
  'syn61786218.csv',
  'syn61375761.csv',
  'syn61375756.csv',
  'syn61375807.csv',
  'syn61375754.csv'],
 '9b7673a467d1e44aa4357a80b223f4b6': ['syn24988814.txt',
  'syn24988812.txt',
  'syn24988813.txt'],
 'e2afd38f3c231b8105e24e8d7fb40b3e': ['syn62060680.csv',
  'syn62060697.csv',
  'syn62060683.csv',
  'syn62060669.csv',
  'syn62060696.csv',
  'syn62060679.csv',
  'syn62060676.csv',
  'syn62060702.csv',
  'syn62060703.csv',
  'syn62060677.csv',
  'syn62060700.csv',
  'syn62060674.csv',
  'syn62060670.csv',
  'syn62060671.csv',
  'syn62060667.csv',
  'syn62060673.csv',
  'syn62060666.csv',
  'syn62060699.csv'],
 '55e79d4c1384a3e138146e89414c8a24': ['syn24988828.txt',
  'syn24988821.txt',
  'syn24988822.txt',
  'syn24988823.txt'],
 'd8be25985e8a7ab1b4ee71dfa1d6d934': ['syn62060657.csv',
  'syn62060737.csv',
  'syn62060654.csv',
  'syn62060651.csv',
  'syn62060645.csv',
  'syn62060652.csv',
  'syn62060741.csv',
  'syn62060747.csv',
  'syn62060751.csv',
  'syn62060745.csv',
  'syn62060744.csv',
  'syn62060750.csv',
  'syn62060748.csv',
  'syn62060662.csv',
  'syn62060663.csv',
  'syn62060649.csv',
  'syn62060660.csv',
  'syn62060664.csv',
  'syn62060658.csv',
  'syn62060739.csv'],
 '55baf60d6ba4765f4585f64c69df5620': ['syn61786220.csv',
  'syn61375766.csv',
  'syn61375799.csv',
  'syn61375809.csv',
  'syn61375808.csv',
  'syn61786219.csv',
  'syn61375775.csv',
  'syn61375778.csv',
  'syn61375800.csv',
  'syn61375812.csv',
  'syn61375813.csv',
  'syn61375797.csv',
  'syn61375768.csv'],
 'dc9628927903f8e91017d4486bce7ef8': ['syn69693741.csv',
  'syn69693747.csv',
  'syn69693744.csv',
  'syn69693695.csv',
  'syn69693709.csv',
  'syn69693735.csv',
  'syn69693720.csv',
  'syn69693697.csv',
  'syn69693718.csv',
  'syn69693725.csv',
  'syn69693733.csv',
  'syn69693702.csv',
  'syn69693728.csv',
  'syn69693714.csv',
  'syn69692769.csv',
  'syn69693705.csv',
  'syn69693711.csv',
  'syn69693738.csv',
  'syn69693699.csv',
  'syn69693706.csv'],
 '883a714830eca1c74b211ee2ef85cb3e': ['syn62060723.csv',
  'syn62060695.csv',
  'syn62060708.csv',
  'syn62060720.csv',
  'syn62060734.csv',
  'syn62060721.csv',
  'syn62060692.csv',
  'syn62060686.csv',
  'syn62060731.csv',
  'syn62060718.csv',
  'syn62060724.csv',
  'syn62060687.csv',
  'syn62060693.csv',
  'syn62060726.csv',
  'syn62060690.csv',
  'syn62060716.csv',
  'syn62060717.csv',
  'syn62060729.csv',
  'syn62060714.csv',
  'syn62060704.csv',
  'syn62060710.csv',
  'syn62060711.csv',
  'syn62060707.csv',
  'syn62060706.csv'],
 'aac0ed5b5cd21f55fc8cac34eda31ce3': ['syn28564555.csv',
  'syn28564568.csv',
  'syn28564636.csv',
  'syn28564408.csv',
  'syn28564595.csv',
  'syn28564609.csv',
  'syn28564194.csv',
  'syn28564553.csv',
  'syn28564591.csv',
  'syn28564181.csv',
  'syn28564418.csv',
  'syn28564183.csv',
  'syn28564236.csv',
  'syn28564223.csv',
  'syn28564196.csv',
  'syn28564522.csv',
  'syn28564292.csv',
  'syn28564290.csv',
  'syn28564257.csv',
  'syn28564647.csv',
  'syn28564684.csv',
  'syn28564679.csv',
  'syn28564533.csv',
  'syn28564268.csv',
  'syn28564714.csv',
  'syn28564648.csv',
  'syn28564474.csv',
  'syn28564689.csv',
  'syn28564266.csv',
  'syn28564707.csv',
  'syn28564713.csv',
  'syn28564539.csv',
  'syn28564706.csv',
  'syn28564699.csv',
  'syn28564711.csv',
  'syn28564603.csv',
  'syn28564210.csv',
  'syn28564600.csv',
  'syn28564628.csv',
  'syn28564177.csv',
  'syn28564559.csv'],
 'b260554887d7f031b60d8c0d5a53ae99': ['syn69693740.csv',
  'syn69693742.csv',
  'syn69693743.csv',
  'syn69693746.csv',
  'syn69693745.csv',
  'syn69693736.csv',
  'syn69693722.csv',
  'syn69693723.csv',
  'syn69693737.csv',
  'syn69693694.csv',
  'syn69693696.csv',
  'syn69693721.csv',
  'syn69693734.csv',
  'syn69693708.csv',
  'syn69693693.csv',
  'syn69693724.csv',
  'syn69693730.csv',
  'syn69693719.csv',
  'syn69693731.csv',
  'syn69693692.csv',
  'syn69693727.csv',
  'syn69693726.csv',
  'syn69693732.csv',
  'syn69693717.csv',
  'syn69693703.csv',
  'syn69693716.csv',
  'syn69692768.csv',
  'syn69693700.csv',
  'syn69693715.csv',
  'syn69693701.csv',
  'syn69693729.csv',
  'syn69693739.csv',
  'syn69693710.csv',
  'syn69693704.csv',
  'syn69693712.csv',
  'syn69693707.csv',
  'syn69693713.csv',
  'syn69693698.csv',
  'syn69693748.csv',
  'syn69693749.csv'],
 'f6dec771366eea2a2372a3c772622a67': ['syn28564622.csv',
  'syn28564556.csv',
  'syn28564231.csv',
  'syn28564225.csv',
  'syn28564184.csv',
  'syn28564631.csv',
  'syn28564618.csv',
  'syn28564624.csv',
  'syn28564237.csv',
  'syn28564627.csv',
  'syn28564182.csv',
  'syn28564708.csv',
  'syn28564523.csv',
  'syn28564457.csv',
  'syn28564695.csv',
  'syn28564524.csv',
  'syn28564256.csv',
  'syn28564280.csv',
  'syn28564240.csv',
  'syn28564254.csv',
  'syn28564259.csv',
  'syn28564700.csv',
  'syn28564660.csv',
  'syn28564288.csv',
  'syn28564710.csv',
  'syn28564399.csv',
  'syn28564206.csv',
  'syn28564207.csv',
  'syn28564198.csv',
  'syn28564211.csv',
  'syn28564238.csv',
  'syn28564610.csv',
  'syn28564599.csv',
  'syn28564214.csv',
  'syn28564228.csv',
  'syn28564567.csv',
  'syn28564613.csv'],
 'd3bdbe903974d914cd49a727289bce20': ['syn24988815.txt',
  'syn24988817.txt',
  'syn24988816.txt'],
 'fdcbf92a4926312519e61e6063382eef': ['syn24988801.txt',
  'syn24988803.txt',
  'syn24988802.txt',
  'syn24988810.txt'],
 'f65d04b589417bc3f57bd157882aab90': ['syn31822647.txt',
  'syn24988820.txt',
  'syn24988818.txt',
  'syn24988819.txt'],
 '0ec8b4343ebf1b97417bd0331d15f939': ['syn62060640.csv',
  'syn62060536.csv',
  'syn62060537.csv',
  'syn62060641.csv',
  'syn62060533.csv',
  'syn62060532.csv',
  'syn62060530.csv',
  'syn62060531.csv',
  'syn62060557.csv',
  'syn62060635.csv',
  'syn62060609.csv',
  'syn62060637.csv',
  'syn62060569.csv',
  'syn62060583.csv',
  'syn62060626.csv',
  'syn62060551.csv',
  'syn62060633.csv',
  'syn62060553.csv',
  'syn62060547.csv',
  'syn62060546.csv',
  'syn62060552.csv',
  'syn62060629.csv',
  'syn62060615.csv',
  'syn62060576.csv',
  'syn62060628.csv',
  'syn62060616.csv',
  'syn62060602.csv',
  'syn62060548.csv',
  'syn62060574.csv',
  'syn62060575.csv',
  'syn62060549.csv',
  'syn62060603.csv',
  'syn62060617.csv',
  'syn62060565.csv',
  'syn62060571.csv',
  'syn62060570.csv',
  'syn62060564.csv',
  'syn62060606.csv',
  'syn62060612.csv',
  'syn62060604.csv',
  'syn62060610.csv',
  'syn62060638.csv',
  'syn62060599.csv',
  'syn62060572.csv',
  'syn62060566.csv',
  'syn62060611.csv',
  'syn62060605.csv'],
 '02cdf8d157c2f5c0ade3569d1258573e': ['syn53296999.txt',
  'syn53297002.txt',
  'syn53297003.txt',
  'syn53297021.txt',
  'syn53297024.txt',
  'syn53297026.txt',
  'syn53296996.txt',
  'syn53296997.txt',
  'syn53296993.txt'],
 'a0a7a118da7890554325a79ec9b491db': ['syn61375788.csv', 'syn61375757.csv'],
 '0ada8d7d5ba99bdb986f69bb533e08fd': ['syn53296998.txt',
  'syn53297029.txt',
  'syn53297015.txt',
  'syn53297001.txt',
  'syn53297000.txt',
  'syn53297005.txt',
  'syn53297011.txt',
  'syn53297013.txt',
  'syn53297022.txt',
  'syn53335480.txt',
  'syn53297019.txt',
  'syn53297018.txt',
  'syn53297030.txt',
  'syn53297027.txt',
  'syn53296994.txt'],
 '25becc931fd0ea259f21ab3cf2abcf28': ['syn24988839.txt',
  'syn24988842.txt',
  'syn24988840.txt'],
 '67cb5fced46ea97fd4d54231bbbff0e7': ['syn61518067.csv',
  'syn61518073.csv',
  'syn62178244.csv',
  'syn61518068.csv'],
 '6826d28b749ee48037c8da9615d3544b': ['syn26720997.csv', 'syn26643855.csv'],
 'c1a2604cc22c7654b26a283276044cad': ['syn26535404.csv',
  'syn26535406.csv',
  'syn26535403.csv'],
 '48b8741e44d3ea4f8e0dc9620867796b': ['syn62060634.csv',
  'syn62060595.csv',
  'syn62060581.csv',
  'syn62060580.csv',
  'syn62060594.csv',
  'syn69075438.csv',
  'syn62060582.csv',
  'syn62060596.csv',
  'syn62060568.csv',
  'syn62060597.csv',
  'syn69075439.csv',
  'syn62060593.csv',
  'syn62060578.csv',
  'syn62060579.csv',
  'syn62060592.csv',
  'syn62060586.csv',
  'syn62060584.csv',
  'syn62060618.csv',
  'syn69075432.csv',
  'syn62060588.csv',
  'syn62060577.csv',
  'syn62060563.csv',
  'syn62060562.csv',
  'syn62060589.csv',
  'syn62060614.csv',
  'syn69075433.csv',
  'syn69075431.csv',
  'syn62060560.csv',
  'syn62060561.csv',
  'syn69075434.csv',
  'syn69075435.csv',
  'syn69075437.csv',
  'syn62060567.csv',
  'syn69075436.csv',
  'syn69075443.csv',
  'syn69075440.csv',
  'syn69075441.csv'],
 '9fa4d65d3153b9ac91c73f889eac4d20': ['syn25547844.csv', 'syn25838632.csv'],
 'edf08e1c613688eb2c076923bbae4f31': ['syn26486792.csv',
  'syn26486790.csv',
  'syn26486784.csv',
  'syn26486782.csv',
  'syn26486776.csv',
  'syn26486774.csv'],
 '8cab6bfb5753663c397d2ac196971494': ['syn53271288.csv',
  'syn53271248.csv',
  'syn53271274.csv',
  'syn53271256.csv',
  'syn53271244.csv',
  'syn53271279.csv',
  'syn53271251.csv',
  'syn53271286.csv'],
 '350d4098ee8ee3346e646d0a12dbdf08': ['syn53271277.csv', 'syn53271262.csv'],
 '9c6e9c0b8114a13e788fc1f1f2a2ffb6': ['syn26486778.csv',
  'syn26486780.csv',
  'syn26486770.csv',
  'syn26486772.csv',
  'syn26486788.csv'],
 '2939ef6c6c36c4027fd079eb9f180f61': ['syn53297017.txt',
  'syn53297014.txt',
  'syn53297028.txt',
  'syn53297010.txt',
  'syn53297020.txt',
  'syn53297009.txt'],
 '4205336dc0ee7ca67ab7bff62484f385': ['syn53271276.csv', 'syn53271252.csv'],
 'f68094fbc9c09205f703ed9e353975c2': ['syn26486750.csv',
  'syn26486752.csv',
  'syn26486753.csv',
  'syn26486756.csv',
  'syn26486758.csv'],
 '10247040a2ab142c6ce1910225a29022': ['syn53271289.csv',
  'syn53271287.csv',
  'syn53282019.csv'],
 '82919fd30cf72b68b5014efeb443abea': ['syn52287352.csv', 'syn52287355.csv'],
 'e14ed18f89757e9b0301eb91a4c964a2': ['syn24988860.txt', 'syn24988859.txt'],
 '61fdb10ae8da4fdbb7ba9e4216aaf103': ['syn24988848.txt',
  'syn24988855.txt',
  'syn24988854.txt',
  'syn24988850.txt',
  'syn24988845.txt',
  'syn24988851.txt',
  'syn24988852.txt'],
 'bd940309f07f1859404c3de08fc604eb': ['syn53271275.csv',
  'syn53271271.csv',
  'syn53271265.csv',
  'syn53271264.csv',
  'syn53271281.csv',
  'syn53271257.csv',
  'syn53271268.csv',
  'syn53282020.csv'],
 'a7b3fe63f18fe3ce5f96c02423edf9b4': ['syn53297004.txt', 'syn53297008.txt'],
 '152c1b2b48a7e0c97de235b6b0d8d981': ['syn53271259.csv',
  'syn53271270.csv',
  'syn53271266.csv',
  'syn53271267.csv',
  'syn53271269.csv',
  'syn53271254.csv',
  'syn53271283.csv',
  'syn53271245.csv',
  'syn53271285.csv'],
 '7ddedaee5def49458c3eb2b6a6c25c54': ['syn53271258.csv',
  'syn53271273.csv',
  'syn53271278.csv'],
 'e0e66b7b732d2a9e0c8c539e309f0e66': ['syn24988858.txt',
  'syn24988856.txt',
  'syn24988857.txt'],
 'fbca977f2ec6f045ae25240193e2224f': ['syn26535417.csv', 'syn26535401.csv'],
 '82d12f4d05c4d07314d7ffaf8b21845e': ['syn53271272.csv',
  'syn53271282.csv',
  'syn53271246.csv'],
 'd8b71b484df8d768e9e540f3f7808705': ['syn53297012.txt',
  'syn53335483.txt',
  'syn53297031.txt'],
 '01ddeca99e76f864d5cdcd3b71465867': ['syn53297023.txt', 'syn53297025.txt'],
 '3f3baca5c95dcd795eacaf009c08c316': ['syn24988843.txt', 'syn24988844.txt'],
 '764abb8add225ecb4201f3e62a5cb007': ['syn26643858.csv', 'syn26720998.csv'],
 'b1986d159a73bfcf37a4883447e3b0f5': ['syn53271284.csv', 'syn53271253.csv'],
 '1bec9bce48204106392410fc70f4d824': ['syn53271247.csv', 'syn53282018.csv'],
 '7b1dc9914392cbeff5c61a717eed2f92': ['syn61375787.csv',
  'syn61375815.csv',
  'syn61375795.csv'],
 '37ba079e5f23cdb5b55f0141bee47e40': ['syn61375751.csv',
  'syn61786217.csv',
  'syn61375752.csv',
  'syn61375794.csv'],
 'f9add95d2c4938a08cb12d05e0a41940': ['syn24988834.txt',
  'syn24988833.txt',
  'syn24988832.txt']}

In [6]:
# Based on the deduplication above write a function to parse each tsv or csv in the dict 
# into json with the file hash as the key

# the json should be flat and therefore have
# row_hash, row_content as dict, and file_paths as list
# and be deduiplicated based on row content

# we can also drp these keys
# "Component": "ImagingLevel2", "Filename": "mxif_level_2/AFsubtracted/HTA11_3252_20000010115220260050000000000.tif", "File Format": "tif", "HTAN Participant ID": "HTA11_3252", "HTAN Parent Biospecimen ID": "HTA11_3252_2000001011", "HTAN Data File ID": "HTA11_3252_20000010115220260050000000000", "Channel Metadata Filename": "mxif_level_2/AFsubtracted/metadata/HTA11_3252_20000010115220260050000000000_metadata.csv", "Imaging Assay Type": "MxIF", "Protocol Link": "NONE", "Workflow Start Datetime": "09/29/2020", "Workflow End Datetime": "09/30/2020", "Software and Version": "ImageApp 1.0.0.0", "Microscope": "INCELL ANALYZER 2500 HS", "Objective": "NIKON MRD00205 Plan Apochromat", "NominalMagnification": "20X", "LensNA": 0.75, "WorkingDistance": 1, "WorkingDistanceUnit": "mm", "Immersion": "Air", "Pyramid": "No", "Zstack": "Yes", "Tseries": "No", "Passed QC": "Yes", "Comment": NaN, "FOV number": NaN, "FOVX": NaN, "FOVXUnit": NaN, "FOVY": NaN, "FOVYUnit": NaN, "Frame Averaging": NaN, "Image ID": "MAP03252_0000_06_04_005\\AFR\\MAP03252_0000_06_04_005_ERBB2_AFR.tif", "DimensionOrder": "XYCZT", "PhysicalSizeX": 0.325, "PhysicalSizeXUnit": "µm", "PhysicalSizeY": 0.325, "PhysicalSizeYUnit": "µm", "PhysicalSizeZ": 0, "PhysicalSizeZUnit": "µm", "Pixels BigEndian": false, "PlaneCount": 0, "SizeC": 26, "SizeT": 0, "SizeX": 9375, "SizeY": 9402, "SizeZ": 0, "PixelType": "uint16", "LEVEL": "2-Processed", "TYPE": "3-AFsubtracted", "LAYERS": 26, "REGION": 5, "POSITION": 0, "LAYER": 12, "ROUND": 17, 


def parse_metadata_to_json(directory):
    result = []
    seen_rows = {}

    for file in files:
        if file.endswith('.tsv') or file.endswith('.csv'):
            file_path = os.path.join(directory, file)
            # regex match syn\d+ to get file_synid
            file_synid = None
            match = re.search(r'syn\d+', file)
            if match:
                file_synid = match.group(0)
            
            try:
                if file.endswith('.tsv'):
                    df = pd.read_csv(file_path, sep='\t', encoding='utf-8')
                else:
                    df = pd.read_csv(file_path, encoding='utf-8')
            except UnicodeDecodeError:
                try:
                    if file.endswith('.tsv'):
                        df = pd.read_csv(file_path, sep='\t', encoding='latin1')
                    else:
                        df = pd.read_csv(file_path, encoding='latin1')
                except Exception as e:
                    print(f"Error reading {file_path}: {e}")
                    continue

            for _, row in df.iterrows():
                row_content = row.to_dict()
                # drop the keys we don't need see above
                keys_to_drop = [
                    "Component",
                    "Filename",
                    "File Format", 
                    "HTAN Participant ID", 
                    "HTAN Parent Biospecimen ID",
                    "HTAN Data File ID", 
                    "Channel Metadata Filename", 
                    "Imaging Assay Type", 
                    "Protocol Link", 
                    "Workflow Start Datetime",
                      "Workflow End Datetime", 
                      "Software and Version", 
                      "Microscope", 
                      "Objective", 
                      "NominalMagnification", 
                      "LensNA", 
                      "WorkingDistance",
                      "WorkingDistanceUnit",
                      "Pyramid","Zstack", "Tseries", "Passed QC", "Comment", "FOV number", 
                      "FOVX", "FOVXUnit", "FOVY", "FOVYUnit", "Frame Averaging", 
                      "Image ID",
                      "DimensionOrder", "PhysicalSizeX", "PhysicalSizeXUnit", 
                      "PhysicalSizeY", 
                      "PhysicalSizeYUnit", 
                      "PhysicalSizeZ", 
                      "PhysicalSizeZUnit",
                      "Pixels BigEndian", 
                      "PlaneCount",
                        "SizeC", "SizeT", "SizeX", "SizeY", "SizeZ", "PixelType", 
                        "LEVEL", "TYPE", "LAYERS", 
                        "REGION", "POSITION", "LAYER", "ROUND"] 
                
                for key in keys_to_drop:
                    row_content.pop(key, None)

                row_str = json.dumps(row_content, sort_keys=True)
                row_hash = hashlib.md5(row_str.encode('utf-8')).hexdigest()

                if row_hash in seen_rows:
                    # Add file path to existing entry
                    seen_rows[row_hash]['ch_synids'].append(file_synid)
                else:
                    # Create new entry
                    entry = {
                        'row_hash': row_hash,
                        'row_content': row_content,
                        'ch_synids': [file_synid]
                    }
                    seen_rows[row_hash] = entry
                    result.append(entry)

    return result

metadata_json = parse_metadata_to_json(directory)

print(f"Parsed {len(metadata_json)} unique rows from metadata files into JSON format.")

Parsed 3647 unique rows from metadata files into JSON format.

In [54]:
metadata_json[2:]  # show last 2 entries

[{'row_hash': '45803a4b40c470cccfd0f6e7d2b9090e',
  'row_content': {'Immersion': 'Air',
   'CHANNEL': 'Cy3',
   'MARKERID': 11,
   'MARKERNAME': 'Beta-Catenin',
   'AbID': nan,
   'CLONE': '12F751',
   'DYE': 'Dylight 550',
   'VENDOR': 'Vanderbilt Antibody and Protein Resource',
   'CATNUM': nan,
   'EXPOSURE(ms)': 50,
   'DILUTION': 0.18056},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': '3beeed44291c4a55cfa346f4ad59fffd',
  'row_content': {'Immersion': 'Air',
   'CHANNEL': 'GFP',
   'MARKERID': 8,
   'MARKERNAME': 'CD11B',
   'AbID': 'AB_2650514',
   'CLONE': 'C67F154',
   'DYE': 'A488',
   'VENDOR': 'Abcam',
   'CATNUM': 'ab133357',
   'EXPOSURE(ms)': 100,
   'DILUTION': 0.11111},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126381',
   'syn25126432',
   'syn25126368',
   'syn25126369',
   'syn25126433',
   'syn25126382',
   'syn25126392',
   'syn25126386',
   'syn25126423',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126390',
   'syn25126384',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126461',
   'syn25126462',
   'syn25126463',
   'syn25126362',
   'syn25126439',
   'syn25126363',
   'syn25126388',
   'syn25126406',
   'syn25126370',
   'syn25126416',
   'syn25126364',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126415',
   'syn25126414',
   'syn25126366']},
 {'row_hash': 'ce7741fc0da0adb15b4a0fb5fa947ae5',
  'row_content': {'Immersion': 'Air',
   'CHANNEL': 'Cy5',
   'MARKERID': 9,
   'MARKERNAME': 'CD20',
   'AbID': nan,
   'CLONE': 'D-10',
   'DYE': 'A647',
   'VENDOR': 'Santa Cruz',
   'CATNUM': 'sc-393894',
   'EXPOSURE(ms)': 50,
   'DILUTION': 0.14583},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': '09c1942efdc37d825b122de9bf6a073b',
  'row_content': {'Immersion': 'Air',
   'CHANNEL': 'Cy3',
   'MARKERID': 17,
   'MARKERNAME': 'CD3d',
   'AbID': 'AB_2788789',
   'CLONE': 'EP4426',
   'DYE': 'A555',
   'VENDOR': 'Abcam',
   'CATNUM': 'ab208514',
   'EXPOSURE(ms)': 100,
   'DILUTION': 0.11111},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': '8250af52edfe0cd816c7f8bf324c6004',
  'row_content': {'Immersion': 'Air',
   'CHANNEL': 'Cy5',
   'MARKERID': 31,
   'MARKERNAME': 'CD45',
   'AbID': 'AB_493034',
   'CLONE': 'H130',
   'DYE': 'A647',
   'VENDOR': 'Biolegend',
   'CATNUM': '304020',
   'EXPOSURE(ms)': 100,
   'DILUTION': 0.11111},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126381',
   'syn25126432',
   'syn25126368',
   'syn25126369',
   'syn25126433',
   'syn25126382',
   'syn25126392',
   'syn25126386',
   'syn25126423',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126390',
   'syn25126384',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126461',
   'syn25126462',
   'syn25126463',
   'syn25126362',
   'syn25126439',
   'syn25126363',
   'syn25126388',
   'syn25126406',
   'syn25126370',
   'syn25126416',
   'syn25126364',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126415',
   'syn25126414',
   'syn25126366']},
 {'row_hash': 'f9c99c0b2e7cae7a72cc82d98ddaa811',
  'row_content': {'Immersion': 'Air',
   'CHANNEL': 'Cy5',
   'MARKERID': 15,
   'MARKERNAME': 'CD4',
   'AbID': 'AB_2750883',
   'CLONE': 'EPR6855',
   'DYE': 'A647',
   'VENDOR': 'Abcam',
   'CATNUM': 'ab133616',
   'EXPOSURE(ms)': 200,
   'DILUTION': 0.18056},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': '5864cbbfc418bffe3852d47f2f7c341c',
  'row_content': {'Immersion': 'Air',
   'CHANNEL': 'Cy3',
   'MARKERID': 23,
   'MARKERNAME': 'CD68',
   'AbID': 'AB_627158',
   'CLONE': 'KP1',
   'DYE': 'A546',
   'VENDOR': 'Santa Cruz',
   'CATNUM': 'sc-20060',
   'EXPOSURE(ms)': 50,
   'DILUTION': 0.18056},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': '258d9af17b6636cfa5bdb95410d67693',
  'row_content': {'Immersion': 'Air',
   'CHANNEL': 'Cy5',
   'MARKERID': 21,
   'MARKERNAME': 'CD8',
   'AbID': nan,
   'CLONE': 'C8/114B',
   'DYE': 'A647',
   'VENDOR': 'Biolegend',
   'CATNUM': '13983',
   'EXPOSURE(ms)': 150,
   'DILUTION': 0.18056},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': '191f80e0d77c852964b8229fd24d6ddf',
  'row_content': {'Immersion': 'Air',
   'CHANNEL': 'Cy3',
   'MARKERID': 14,
   'MARKERNAME': 'CgA',
   'AbID': 'AB_2801371',
   'CLONE': 'C-12',
   'DYE': 'A546',
   'VENDOR': 'Santa Cruz',
   'CATNUM': 'sc-393941',
   'EXPOSURE(ms)': 50,
   'DILUTION': 0.09375},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': '77768e79a28ec89ac5921a4bc87a831b',
  'row_content': {'Immersion': 'Air',
   'CHANNEL': 'Cy3',
   'MARKERID': 6,
   'MARKERNAME': 'Collagen',
   'AbID': nan,
   'CLONE': 'CHP',
   'DYE': 'Cy3',
   'VENDOR': '3Helix',
   'CATNUM': 'R-CHP',
   'EXPOSURE(ms)': 10,
   'DILUTION': 0.25},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126381',
   'syn25126432',
   'syn25126368',
   'syn25126369',
   'syn25126433',
   'syn25126382',
   'syn25126392',
   'syn25126386',
   'syn25126423',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126390',
   'syn25126384',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126461',
   'syn25126462',
   'syn25126463',
   'syn25126362',
   'syn25126439',
   'syn25126363',
   'syn25126388',
   'syn25126406',
   'syn25126370',
   'syn25126416',
   'syn25126364',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126415',
   'syn25126414',
   'syn25126366']},
 {'row_hash': '693119bd5152f1a6d1e01ca117e79f34',
  'row_content': {'Immersion': 'Air',
   'CHANNEL': 'Cy5',
   'MARKERID': 30,
   'MARKERNAME': 'ERBB2',
   'AbID': 'AB_2889201',
   'CLONE': 'MAb414',
   'DYE': 'A647',
   'VENDOR': 'Abcam',
   'CATNUM': 'ab225510',
   'EXPOSURE(ms)': 500,
   'DILUTION': 0.14583},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': '8c7797411d781e9338fcf2b5fde3513f',
  'row_content': {'Immersion': 'Air',
   'CHANNEL': 'Cy5',
   'MARKERID': 27,
   'MARKERNAME': 'FOXP3',
   'AbID': 'AB_439753',
   'CLONE': '206D',
   'DYE': 'A647',
   'VENDOR': 'Biolegend',
   'CATNUM': '320113',

In [9]:
# sample 5 random entries
metadata_json_small = random.sample(metadata_json, 5)

In [10]:
# show mne entries that have more than one file path
[file for file in metadata_json if len(file['ch_synids']) > 1]

[{'row_hash': '7ab2d47382209674e5eddf4b7ed05fe5',
  'row_content': {'WorkingDistanceUnit': 'mm',
   'Immersion': 'Air',
   'Pyramid': 'No',
   'CHANNEL': 'UV',
   'MARKERID': 4,
   'MARKERNAME': 'DAPI',
   'AbID': nan,
   'CLONE': nan,
   'DYE': 'DAPI',
   'VENDOR': 'Sigma-Aldrich',
   'CATNUM': 'T9284',
   'EXPOSURE(ms)': 20,
   'DILUTION': 0.1},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': '9089bb7bec468d709780edd5eeb6f10d',
  'row_content': {'WorkingDistanceUnit': 'mm',
   'Immersion': 'Air',
   'Pyramid': 'No',
   'CHANNEL': 'GFP',
   'MARKERID': 22,
   'MARKERNAME': 'Alpha-actinin 4',
   'AbID': nan,
   'CLONE': 'EPR2533(2)',
   'DYE': 'A488',
   'VENDOR': 'Abcam',
   'CATNUM': 'ab198608',
   'EXPOSURE(ms)': 100,
   'DILUTION': 0.11111},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': '08dc71fce97dacabf0f431b557129491',
  'row_content': {'WorkingDistanceUnit': 'mm',
   'Immersion': 'Air',
   'Pyramid': 'No',
   'CHANNEL': 'Cy3',
   'MARKERID': 11,
   'MARKERNAME': 'Beta-Catenin',
   'AbID': nan,
   'CLONE': '12F751',
   'DYE': 'Dylight 550',
   'VENDOR': 'Vanderbilt Antibody and Protein Resource',
   'CATNUM': nan,
   'EXPOSURE(ms)': 50,
   'DILUTION': 0.18056},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': '2c78bdff6bf12573097f9a589a474c2e',
  'row_content': {'WorkingDistanceUnit': 'mm',
   'Immersion': 'Air',
   'Pyramid': 'No',
   'CHANNEL': 'GFP',
   'MARKERID': 8,
   'MARKERNAME': 'CD11B',
   'AbID': 'AB_2650514',
   'CLONE': 'C67F154',
   'DYE': 'A488',
   'VENDOR': 'Abcam',
   'CATNUM': 'ab133357',
   'EXPOSURE(ms)': 100,
   'DILUTION': 0.11111},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126381',
   'syn25126432',
   'syn25126368',
   'syn25126369',
   'syn25126433',
   'syn25126382',
   'syn25126392',
   'syn25126386',
   'syn25126423',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126390',
   'syn25126384',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126461',
   'syn25126462',
   'syn25126463',
   'syn25126362',
   'syn25126439',
   'syn25126363',
   'syn25126388',
   'syn25126406',
   'syn25126370',
   'syn25126416',
   'syn25126364',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126415',
   'syn25126414',
   'syn25126366']},
 {'row_hash': '0b85d9d3033dd1831c5e5c8f1f7d26ff',
  'row_content': {'WorkingDistanceUnit': 'mm',
   'Immersion': 'Air',
   'Pyramid': 'No',
   'CHANNEL': 'Cy5',
   'MARKERID': 9,
   'MARKERNAME': 'CD20',
   'AbID': nan,
   'CLONE': 'D-10',
   'DYE': 'A647',
   'VENDOR': 'Santa Cruz',
   'CATNUM': 'sc-393894',
   'EXPOSURE(ms)': 50,
   'DILUTION': 0.14583},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': '171f9ca08f92658e7bae8cfddb1e1911',
  'row_content': {'WorkingDistanceUnit': 'mm',
   'Immersion': 'Air',
   'Pyramid': 'No',
   'CHANNEL': 'Cy3',
   'MARKERID': 17,
   'MARKERNAME': 'CD3d',
   'AbID': 'AB_2788789',
   'CLONE': 'EP4426',
   'DYE': 'A555',
   'VENDOR': 'Abcam',
   'CATNUM': 'ab208514',
   'EXPOSURE(ms)': 100,
   'DILUTION': 0.11111},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': 'd6d5b12909627e7591ada4a2896014cd',
  'row_content': {'WorkingDistanceUnit': 'mm',
   'Immersion': 'Air',
   'Pyramid': 'No',
   'CHANNEL': 'Cy5',
   'MARKERID': 31,
   'MARKERNAME': 'CD45',
   'AbID': 'AB_493034',
   'CLONE': 'H130',
   'DYE': 'A647',
   'VENDOR': 'Biolegend',
   'CATNUM': '304020',
   'EXPOSURE(ms)': 100,
   'DILUTION': 0.11111},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126381',
   'syn25126432',
   'syn25126368',
   'syn25126369',
   'syn25126433',
   'syn25126382',
   'syn25126392',
   'syn25126386',
   'syn25126423',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126390',
   'syn25126384',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126461',
   'syn25126462',
   'syn25126463',
   'syn25126362',
   'syn25126439',
   'syn25126363',
   'syn25126388',
   'syn25126406',
   'syn25126370',
   'syn25126416',
   'syn25126364',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126415',
   'syn25126414',
   'syn25126366']},
 {'row_hash': 'd495d01cc43a25726ff9d9c4850a02b0',
  'row_content': {'WorkingDistanceUnit': 'mm',
   'Immersion': 'Air',
   'Pyramid': 'No',
   'CHANNEL': 'Cy5',
   'MARKERID': 15,
   'MARKERNAME': 'CD4',
   'AbID': 'AB_2750883',
   'CLONE': 'EPR6855',
   'DYE': 'A647',
   'VENDOR': 'Abcam',
   'CATNUM': 'ab133616',
   'EXPOSURE(ms)': 200,
   'DILUTION': 0.18056},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': '126bccf894f6f49fea54610f290040d9',
  'row_content': {'WorkingDistanceUnit': 'mm',
   'Immersion': 'Air',
   'Pyramid': 'No',
   'CHANNEL': 'Cy3',
   'MARKERID': 23,
   'MARKERNAME': 'CD68',
   'AbID': 'AB_627158',
   'CLONE': 'KP1',
   'DYE': 'A546',
   'VENDOR': 'Santa Cruz',
   'CATNUM': 'sc-20060',
   'EXPOSURE(ms)': 50,
   'DILUTION': 0.18056},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': '66737d1ab7e8fcf8e6eb1913804595a9',
  'row_content': {'WorkingDistanceUnit': 'mm',
   'Immersion': 'Air',
   'Pyramid': 'No',
   'CHANNEL': 'Cy5',
   'MARKERID': 21,
   'MARKERNAME': 'CD8',
   'AbID': nan,
   'CLONE': 'C8/114B',
   'DYE': 'A647',
   'VENDOR': 'Biolegend',
   'CATNUM': '13983',
   'EXPOSURE(ms)': 150,
   'DILUTION': 0.18056},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',
   'syn25126421',
   'syn25126409',
   'syn25126390',
   'syn25126384',
   'syn25126446',
   'syn25126452',
   'syn25126453',
   'syn25126447',
   'syn25126445',
   'syn25126444',
   'syn25126450',
   'syn25126454',
   'syn25126440',
   'syn25126441',
   'syn25126455',
   'syn25126443',
   'syn25126457',
   'syn25126456',
   'syn25126464',
   'syn25126458',
   'syn25126449',
   'syn25126461',
   'syn25126448',
   'syn25126462',
   'syn25126463',
   'syn25126404',
   'syn25126362',
   'syn25126376',
   'syn25126410',
   'syn25126438',
   'syn25126439',
   'syn25126377',
   'syn25126411',
   'syn25126405',
   'syn25126363',
   'syn25126388',
   'syn25126413',
   'syn25126407',
   'syn25126406',
   'syn25126412',
   'syn25126374',
   'syn25126370',
   'syn25126416',
   'syn25126402',
   'syn25126364',
   'syn25126403',
   'syn25126365',
   'syn25126371',
   'syn25126417',
   'syn25126398',
   'syn25126429',
   'syn25126367',
   'syn25126401',
   'syn25126415',
   'syn25126373',
   'syn25126414',
   'syn25126372',
   'syn25126366',
   'syn25126428',
   'syn25126399']},
 {'row_hash': 'bee66ed36b88d5a81e1dd533d231de27',
  'row_content': {'WorkingDistanceUnit': 'mm',
   'Immersion': 'Air',
   'Pyramid': 'No',
   'CHANNEL': 'Cy3',
   'MARKERID': 14,
   'MARKERNAME': 'CgA',
   'AbID': 'AB_2801371',
   'CLONE': 'C-12',
   'DYE': 'A546',
   'VENDOR': 'Santa Cruz',
   'CATNUM': 'sc-393941',
   'EXPOSURE(ms)': 50,
   'DILUTION': 0.09375},
  'ch_synids': ['syn25126380',
   'syn25126394',
   'syn25126425',
   'syn25126431',
   'syn25126419',
   'syn25126418',
   'syn25126430',
   'syn25126424',
   'syn25126395',
   'syn25126381',
   'syn25126397',
   'syn25126383',
   'syn25126432',
   'syn25126426',
   'syn25126368',
   'syn25126369',
   'syn25126427',
   'syn25126433',
   'syn25126382',
   'syn25126396',
   'syn25126392',
   'syn25126386',
   'syn25126379',
   'syn25126423',
   'syn25126422',
   'syn25126378',
   'syn25126387',
   'syn25126393',
   'syn25126385',
   'syn25126391',
   'syn25126420',
   'syn25126434',
   'syn25126435',

In [7]:
# use claude batch api to take row_content and return a "canonical_marker"
from anthropic import Anthropic, transform_schema
from anthropic.types.beta.message_create_params import MessageCreateParamsNonStreaming
from anthropic.types.beta.messages.batch_create_params import Request
import dotenv
dotenv.load_dotenv()

from pydantic import BaseModel, Field
from enum import Enum

# marker type enum can be chemical_stain, blank_or_background, protein_group, protein_single, cd_marker, other_dna, other

class MarkerTypeEnum(str, Enum):
    chemical_stain = "chemical_stain"
    blank_or_background = "blank_or_background" 
    protein_group = "protein_group"
    protein_single = "protein_single"
    chemical_element = "chemical_element"
    cd_marker = "cd_marker"
    other_dna = "other_dna"
    other = "other"

class ExtractedlMarkerSchema(BaseModel):
    extracted_marker: str = Field(..., description="The most relevant canonical marker or identifier for the protein, stain or feature being imaged extracted from the metadata row content.")
    marker_type: MarkerTypeEnum = Field(..., description="The type of the canonical marker.")

client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

In [56]:
# make a single request to test
def get_marker_classification(entry):
    prompt = f"""Given the following imaging metadata row content, extract the most relevant canonical marker or identifier and classify its type. If it looks to be 
Metadata Row Content: {json.dumps(entry['row_content'])}
Return the result in JSON format with the fields 'extracted_marker' and 'marker_type'."""
    response = client.beta.messages.create(
        model="claude-haiku-4-5",
        max_tokens=100,
        temperature=0.0,
        betas=["structured-outputs-2025-11-13"],
        messages=[{
            "role": "user",
            "content": prompt
        }],
        output_format={
            "type": "json_schema",
            "schema": transform_schema(ExtractedlMarkerSchema)
        }
    )
    return response.content[0].text

get_marker_classification(metadata_json_small[0])

'{"extracted_marker": "CK17", "marker_type": "protein_single"}'

In [13]:
import json
import time
from anthropic import Anthropic, transform_schema

client = Anthropic()

def process_all_metadata_with_batch(entries):
    # ... [Batch creation and submission logic same as before] ...
    
    # 1. Create Requests
    requests = []
    for idx, entry in enumerate(entries):
        requests.append({
            "custom_id": str(idx),
            "params": {
                "model": "claude-haiku-4-5",
                "max_tokens": 100,
                "messages": [{"role": "user", "content": json.dumps(entry['row_content'])}],
                "output_format": {
                    "type": "json_schema", 
                    "schema": transform_schema(ExtractedlMarkerSchema)
                }
            }
        })

    # 2. Submit Batch
    batch = client.beta.messages.batches.create(
        requests=requests,
        betas=["structured-outputs-2025-11-13"]
    )
    print(f"Batch {batch.id} submitted.")

    # 3. Wait for Completion
    while True:
        batch = client.beta.messages.batches.retrieve(batch.id)
        print(f"Batch status: {batch.processing_status}")
        if batch.processing_status == "ended":
            break
        time.sleep(10)

    # 4. Map Results and Capture Specific Errors
    results_map = {res.custom_id: res for res in client.beta.messages.batches.results(batch.id)}
    
    enhanced_entries = []
    
    for idx, entry in enumerate(entries):
        entry_enhanced = entry.copy()
        result_obj = results_map.get(str(idx))

        if not result_obj:
            # Case 1: The ID is completely missing from results (rare)
            entry_enhanced['marker_classification'] = {
                "error": "Batch result missing for this ID"
            }
        
        elif result_obj.result.type == "succeeded":
            # Case 2: Success - Parse the JSON content
            try:
                raw_json = result_obj.result.message.content[0].text
                entry_enhanced['marker_classification'] = json.loads(raw_json)
            except json.JSONDecodeError:
                entry_enhanced['marker_classification'] = {
                    "error": "Model returned invalid JSON",
                    "raw_output": raw_json
                }

        elif result_obj.result.type == "errored":
            # Case 3: API Error - Capture the REAL error message
            # The 'error' object typically has 'type' and 'message' fields
            api_error = result_obj.result.error
            error_message = getattr(api_error, "message", str(api_error))
            error_type = getattr(api_error, "type", "unknown_error")
            
            entry_enhanced['marker_classification'] = {
                "error": error_message,
                "error_type": error_type
            }

        else:
            # Case 4: Expired or other status
            entry_enhanced['marker_classification'] = {
                "error": f"Unexpected status: {result_obj.result.type}"
            }
            
        enhanced_entries.append(entry_enhanced)

    return enhanced_entries

enhanced_metadata = process_all_metadata_with_batch(metadata_json_small)

Batch msgbatch_01VNnahyApJRKj7p2PGU3nif submitted.
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: ended

In [14]:
metadata_df_enhanced = pd.DataFrame(enhanced_metadata)
metadata_df_enhanced.head()

,row_hash,row_content,ch_synids,marker_classification
0,5050fae1850cc007335e5d740969842b,"{'Channel ID': 'Channel:25', 'Channel Name': '...","[syn53271277, syn53271262, syn53271258, syn532...","{'extracted_marker': 'CK17', 'marker_type': 'p..."
1,af098cf3ef1e86b240c5172fc77a751c,"{'Channel ID': 'Channel:0:25', 'Channel Name':...",[syn25509688],"{'extracted_marker': 'CD57', 'marker_type': 'c..."
2,93d592dcbce6206faff54a7626347637,"{'filename': 'KB_SMMART_523_D23_C12R1_ASMA', '...",[syn69046893],"{'extracted_marker': 'alpha-SMA', 'marker_type..."
3,88c043e387cb8391d49f1f679cf8606d,{'filename': 'EC_SMMART_85529_D23_C09R1_FOXP3'...,[syn69046902],"{'extracted_marker': 'FOXP3', 'marker_type': '..."
4,bea74da731b34b1f34a672499c8b5b4e,"{'Channel ID': 'Channel:0:15', 'Channel Name':...","[syn26535411, syn26535409]","{'extracted_marker': 'CD8a', 'marker_type': 'c..."

In [15]:
enhanced_metadata = process_all_metadata_with_batch(metadata_json)

Batch msgbatch_01XmnDM4Nt2wAe1aCj1p8Asc submitted.
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: in_progress
Batch status: ended

In [16]:
enhanced_metadata_df_enhanced = pd.DataFrame(enhanced_metadata)
enhanced_metadata_df_enhanced['extracted_marker'] = enhanced_metadata_df_enhanced['marker_classification'].apply(lambda x: x.get('extracted_marker') if isinstance(x, dict) and 'extracted_marker' in x else None)
enhanced_metadata_df_enhanced['marker_type'] = enhanced_metadata_df_enhanced['marker_classification'].apply(lambda x: x.get('marker_type') if isinstance(x, dict) and 'marker_type' in x else None)
enhanced_metadata_df_enhanced.head()

,row_hash,row_content,ch_synids,marker_classification,extracted_marker,marker_type
0,7ab2d47382209674e5eddf4b7ed05fe5,"{'WorkingDistanceUnit': 'mm', 'Immersion': 'Ai...","[syn25126380, syn25126394, syn25126425, syn251...","{'extracted_marker': 'DAPI', 'marker_type': 'c...",DAPI,chemical_stain
1,9089bb7bec468d709780edd5eeb6f10d,"{'WorkingDistanceUnit': 'mm', 'Immersion': 'Ai...","[syn25126380, syn25126394, syn25126425, syn251...","{'extracted_marker': 'Alpha-actinin 4', 'marke...",Alpha-actinin 4,protein_single
2,08dc71fce97dacabf0f431b557129491,"{'WorkingDistanceUnit': 'mm', 'Immersion': 'Ai...","[syn25126380, syn25126394, syn25126425, syn251...","{'extracted_marker': 'Beta-Catenin', 'marker_t...",Beta-Catenin,protein_single
3,2c78bdff6bf12573097f9a589a474c2e,"{'WorkingDistanceUnit': 'mm', 'Immersion': 'Ai...","[syn25126380, syn25126394, syn25126425, syn251...","{'extracted_marker': 'CD11B', 'marker_type': '...",CD11B,cd_marker
4,0b85d9d3033dd1831c5e5c8f1f7d26ff,"{'WorkingDistanceUnit': 'mm', 'Immersion': 'Ai...","[syn25126380, syn25126394, syn25126425, syn251...","{'extracted_marker': 'CD20', 'marker_type': 'c...",CD20,cd_marker

In [17]:
enhanced_metadata_df_enhanced.groupby('marker_type').size()

marker_type
blank_or_background     129
cd_marker              1157
chemical_element         15
chemical_stain          240
other                    44
other_dna               189
protein_group           193
protein_single         1680
dtype: int64

In [18]:
# give 5 most common markers for each marker type
enhanced_metadata_df_enhanced.groupby('marker_type')['extracted_marker'].value_counts().groupby(level=0).head(5)

marker_type          extracted_marker
blank_or_background  blank                  44
                     Empty                  21
                     Blank                  12
                     9999                   10
                     Blank_488               7
cd_marker            CD20                   84
                     CD45                   82
                     CD68                   79
                     CD3                    63
                     CD163                  62
chemical_element     CA1                     2
                     5'-HMC                  1
                     Au                      1
                     Au (Gold, mass 197)     1
                     C-12                    1
chemical_stain       DAPI                   81
                     hematoxylin            34
                     Hoechst 33342          17
                     hemotoxylin             8
                     DAPI2                   5
other                9999                   18
                     ColI                    2
                     EP700Y                  2
                     HEM1                    2
                     HEM3                    2
other_dna            DNA                    85
                     dsDNA                   8
                     DSDNA                   4
                     DAPI                    2
                     DNA_1                   2
protein_group        PanCK                  18
                     Pan-cytokeratin        11
                     pan cytokeratin        10
                     Cytokeratin (pan)       9
                     Pan-CK                  9
protein_single       Ki67                   50
                     FOXP3                  48
                     Granzyme B             36
                     Vimentin               34
                     PD-L1                  32
Name: count, dtype: int64

In [19]:
# number of unuique extracted markers
enhanced_metadata_df_enhanced['extracted_marker'].nunique()

825

In [20]:
# number of unique extracted markers per marker type
enhanced_metadata_df_enhanced.groupby('marker_type')['extracted_marker'].nunique()

marker_type
blank_or_background     32
cd_marker              112
chemical_element        14
chemical_stain          47
other                   23
other_dna               56
protein_group           69
protein_single         524
Name: extracted_marker, dtype: int64

In [21]:
# show the unique markers inb protein_group
enhanced_metadata_df_enhanced[enhanced_metadata_df_enhanced['marker_type'] == 'protein_group']['extracted_marker'].unique()

array(['PanCK', 'HLA II', 'Collagen', 'PanCytokeratin', 'HLA-A',
       'Galectin', 'Pan-Cytokeratin', 'CK8/18', 'SMA', 'Pan Keratin',
       'T1 Collagen', 'TCF1/TCF7', 'Pan CytoKRT', 'HLAII',
       'pan-cytokeratin', 'pan cytokeratin', 'H3NUCA', 'HLA-II',
       'HLA-DR/DP/DQ', 'HLA class I', 'Pan-CK', 'Cytokeratin (Pan)',
       'DAPI1, pHH3, CK14, Ki67, CK19', 'panCK',
       'Donkey anti-Rat IgG-AF488', 'Donkey anti-Rabbit IgG-AF555',
       'Pan-cytokeratin', 'H3K4', 'H3K27ac', 'Lamin A+C', 'H3K27',
       'PanCK-SOX10', 'GP2', 'Goat anti-Rabbit IgG-AF488',
       'Donkey anti-Mouse IgG-AF647', 'Mouse IgG', 'BCA1',
       'MHC class I antigen ABC', 'Rat-IgG', 'Phospho-CDK1/2/3/5 (Tyr15)',
       'IgM', 'cytokeratin', 'TCRyd', 'HLA-ABC', 'PLAT/tPA', 'NaK/ATPase',
       'RNA polymerase II CTD (pS2)', 'FAP', 'Goat IgG',
       'Cytokeratin (pan)', 'HLA-DRA', 'H3K27me3', 'Pan Cytokeratin',
       'Histone H3.1 (K27me3)', 'Rb (pS807; pS811)', 'PAN-CK', 'aSMA',
       'HLA-DR', 'Nuclear pore complex protein Nup98-Nup96',
       'Donkey anti-Rabbit IgG-AF488', 'Pan-KRT', 'LC3A/B',
       'Pan-Cytokeratin (PanCK)', 'Rabbit IgG', 'HLA-DPB1',
       'Goat Anti-Mouse IgG-AF647', 'COlIV', 'NULP1-TCF25',
       'Goat Anti-Mouse IgG-AF488'], dtype=object)

In [22]:
# show the unique markers inb protein_group
enhanced_metadata_df_enhanced[enhanced_metadata_df_enhanced['marker_type'] == 'other_dna']['extracted_marker'].unique()

array(['DSDNA', 'DNA', 'anti DS DNA', 'dsDNA', 'DNA_1', 'DNA_2', 'DAPI',
       'DNA_3', 'DNA_4', 'DNA_5', 'DNA_6', 'DNA_7', 'DNA_9', 'DNA1',
       'DNA2', 'dna1', 'dna2', 'dna3', 'dna4', 'dna5', 'dna6', 'dna7',
       'dna8', 'dna9', 'dna10', 'dna11', 'dna12', 'dna13', 'dna14',
       'dna15', 'dna16', 'dna17', 'dna18', 'dna19', 'dna20', 'dna21',
       'dna22', 'dna23', 'dna24', 'dna25', 'dna26', 'dna27', 'dna28',
       'dna29', 'dna30', 'DNA_8', 'DNA_10', 'DNA_11', 'DNA_13', 'DNA_16',
       'DNA_17', 'DNA_18', 'DNA_19', 'DNA (6)', 'DNA (Hoechst 33342)',
       'DNA (11)'], dtype=object)

In [23]:
# show the unique markers inb protein_group

In [24]:

enhanced_metadata_df_enhanced[enhanced_metadata_df_enhanced['marker_type'] == 'chemical_stain']['extracted_marker'].unique()

array(['DAPI', 'SNA', 'hematoxylin', 'DAPI3', 'DES', 'DRAQ5',
       'hemotoxylin', 'HEM2', 'H&E', 'Syto13', 'DAPI2', 'DAPI1', 'DAPI6',
       'Autofluorescence-488nm', 'Autofluorescence-555nm',
       'Autofluorescence-647nm', 'Hoechst 33342', 'DAPI4', 'DAPI7',
       'DAPI8', 'DAPI9', 'DAPI10', 'Cy5', 'DNA', 'Alexa Fluor 488',
       'Alexa Fluor 555', 'Alexa Fluor 647', 'DAPI5',
       'DNA (Hoechst 33342)', 'Hoechst1', 'Hoechst2', 'Hoechst3',
       'Hoechst4', 'Hoechst5', 'Hoechst6', 'Hoechst7', 'Hoechst8',
       'Hoechst9', 'Hoechst10', 'Hoechst11', 'Hoechst12', 'Hoechst13',
       'TRITC', 'TRITC-AF', 'CY5-AF', 'Hoechst 2', "5'-HMC"], dtype=object)

In [25]:
enhanced_metadata_df_enhanced[enhanced_metadata_df_enhanced['marker_type'] == 'protein_single']['extracted_marker'].unique()

array(['Alpha-actinin 4', 'Beta-Catenin', 'CgA', 'Collagen', 'ERBB2',
       'FOXP3', 'Gamma-Actin', 'HLA-A', 'Lysozyme', 'Muc2', 'NaKATPase',
       'OLFM4', 'PCNA', 'pEGFR', 'p-STAT3', 'SMA', 'Sox9', 'Vimentin',
       'PDL1', 'EOMES', 'DC-LAMP', 'GrzB', 'T-bet', 'Foxp3', 'Ki67',
       'SMOC2', 'BMX', 'Alpha-SMA', 'MUC2', 'MKi67', 'AGR2', 'IGLL5',
       'CHGA', 'MYH11', 'SYNAPTOPHYSIN', 'KRT18', 'PDPN', 'CTNNA2',
       'WNT2B', 'WNT5B', 'RSPO3', 'Cox2', 'ACTG1', 'MUC5AC',
       'Na/K-ATPase', 'AQP5', 'Podoplanin', 'Hepatocyte Paraffin 1',
       'GLUT1', 'CK19', 'E-cadherin', 'MUC-2', 'SOX9', 'FoxP3', 'P21',
       'CK7', 'P16', 'CCL2', 'PAI1', 'CDH1', 'COL6A2', 'ALPHA-SMA', 'CEA',
       'VIMENTIN', 'SLC19A2', 'RUNX1', 'VCAN', 'SOX2', 'MUC1',
       'Beta-catenin', 'GLUT (D)', 'Keratin 14', 'PAI', 'DPEP1',
       'CEACAM5', 'PD-L1', 'LAG3', 'Granzyme B', 'PD-L2', 'Histone H3',
       'Vimentine', 'GLUT', 'HER2', 'ER', 'pHH3', 'CK14', 'CK5', 'PD1',
       'LamAC', 'aSMA', 'EP700Y', 'CK17', 'Hep-Par-1', 'OTOP3', 'REG4',
       'RETNLB', 'SOX17', 'NOVA2', 'HNF4A', 'KRT20', 'COX2/PTGS2',
       'ATP1B1', 'COL6A1', 'BACH1', 'SMARCC1', 'PBX3', 'ASCL2', 'CLDN1',
       'Mki67', 'BEST4', 'DC_LAMP', 'SNA', 'HepPar1', 'Alpha-actinin4',
       'DCLAMP', 'GRZB', 'TBET', 'KI67', 'alpha SMA', 'H3NUCA', 'AR',
       'BCA1', 'LYVE1', 'Aqp2', 'Vim', 'LRP2', 'UMOD', 'CALB1', 'AQP1',
       'CA9', 'UCHL1', 'BAP1', 'Tbet', 'CCR2', 'BMI1', 'RAB6B', 'PDE3A',
       'SSR4', 'LGR5', 'S100', 'PDL-1', 'Her2', 'GATA3', 'TFF1', 'MGP',
       'a-Amylase', 'PR-(D)', 'Bap1', 'COX6c', 'PLAT/tPA', 'CTLA4',
       'SLC39A6', 'Keratin 5', 'GZMB', 'Mouse IgG', 'Ki-67',
       'TBK1 (pS172)', 'TIM-3', 'p60-Src (pY418)', 'STAT1 (pY701)',
       'Desmin', 'hSTING', 'Rb (pS807; pS811)', 'Phospho-Tyrosine',
       'Ecad', 'cPARP', 'EGFR', 'BCL2', 'GRNZB', 'CK8', 'pS6RP', 'CSF1R',
       'CoxIV', 'gH2AX', 'CAV1', 'CCND1', 'pRB', 'RAD51', 'H3K27',
       'ColIV', 'ERK-1 (pT202; pY204)', 'hRAD51', 'Cyclin-D1',
       'Aortic smooth muscle actin', 'ER-alpha', 'PR',
       'Epidermal growth factor receptor', 'p21', 'CK-14', 'CK-19',
       'CK-17', 'Lamin A/C', 'Lamin B1', 'Androgen Receptor',
       'Histone H2AX', 'PD-1', 'Alpha-actinin-4', 'NaKAPTase', 'P-STAT3',
       'E-Cadherin', 'FoxO1', 'H3K27me3', 'Lag3', 'MPO', 'MYC', 'p53',
       'pSTAT5', 'VISTA', 'PgR', 'ColI', 'Actin', 'PR-D',
       'Histone H3 Phosphorylation', 'beta3-integrin', 'HIF1a', 'Maspin',
       'MMP9', 'COX2', 'MLPH', 'Lyve-1', 'beta-integrin', 'P63',
       'Histone H3 phosphorylation', 'Keratin 17', 'pAKT', 'BMP2',
       'TUBB3', 'CC3', 'pERK', '53BP1', 'Glut1', 'LamB1', 'MSH2', 'CGA',
       'LAG-3', 'Alpha-actin-2', 'KRT5', 'collagen 1', 'PD-L1 (SP142)',
       'MHC class II antigen DPB1', 'Rat IgG', 'Rabbit IgG', 'tPA',
       'TCF-1', 'HIF1A', 'cKIT', 'FGFR3',
       'Phospho-RNA polymerase II subunit B1 CTD (Ser2)',
       'Phospho-ERK-1/2 (Thr202, Tyr204)', 'MHC class I antigen ABC',
       'Phospho-40S ribosomal protein S6 (Ser240, Ser244)',
       '40S ribosomal protein S6', 'Collagen alpha-1(IV) chain',
       'Androgen receptor',
       'Phospho-40S ribosomal protein S6 (Ser235, Ser236)',
       'Phospho-protein NDRG1 (Thr346)', 'Phospho-pRb (Ser807, Ser811)',
       'Phospho-tyrosine', 'G1/S-specific cyclin-D1', 'SOX-2', 'Lamin-B1',
       'E2F-1', 'p27Kip1', 'HSP 90', 'Pan-protein kinase Akt',
       'Lamin-A/C', 'Phospho-Histone H2AX (Ser139)', 'Perforin-1',
       'Cyclin-A2', 'MAP-2', 'Phospho-mTOR (Ser2448)',
       'G2/mitotic-specific cyclin-B1', 'GFAP', 'G1/S-specific cyclin-E1',
       'Donkey anti-Rabbit IgG-AF555', 'Cleaved PARP-1', 'CK-7',
       'RP-A p32', 'Iron-sulfur subunit of complex II', 'Protein S100-A4',
       'Catenin beta-1', 'Notch 1', 'COX IV-1',
       'Phospho-serine/threonine-protein kinase TBK1 (Ser172)',
       'Cleaved caspase-3 (Asp175)', 'Apoptosis regulator BAX',
       'Phospho-histone H3.1 (Ser10)', 'Apoptosis inhibitor survivin',
       'Mucin-5AC', 'Tri-methyl-histone H3.1 (Lys27)',
       'Cellular tumor antigen p53', 'Proto-oncogene c-Jun',
       'MHC class II antigen DRA', 'NGF receptor',
       'Forkhead box protein O1', 'EZH2', 'Histone H3.1',
       'Natural cytotoxicity triggering receptor 1', 'mTOR',
       'Serine/threonine-protein kinase B-raf V600E', 'KAP-1',
       'Forkhead box protein A2', 'Donkey anti-Rat IgG-AF488', 'HIF-1a',
       'FAP', 'podoplanin', 'collagen IV', 'MMP12', 'CXCR5', 'vimentin',
       'VIM', 'Pin1', 'ZEB1', 'pMYC', 'pRPA', 'Collagen IV', 'NGFR',
       'IDO1', 'MITF', 'S100A', 'SOX10', 'RNA Pol II CTD (pS2)',
       'Cytokeratin 14', 'Cytokeratin 19', 'Cytokeratin 17',
       'Progesterone receptor', 'Cytokeratin 5', 'ERBB4', 'MYCN', 'ALK',
       'SERCA2', 'ISL1', 'SV2C', 'Nestin', 'HBEGF', 'IL1RAPL1', 'L1CAM',
       'MRP4', 'C1QC', 'NLRP3', 'CLSTN2', 'GPC5', 'GYPC', 'CACNA1C',
       'PPP2R2C', 'TrKB', 'PHOX2B', 'TGFA', 'BMP7',
       'Streptavidin-ArgoFluor 890', 'COX IV', 'HLA-E', 'NKp46/NCR1',
       'alpha-SMA', 'cGAS', 'Histone H2A.X (pS139)', 'pSTAT1',
       'p-TBK1 (pS172)', 'Stat3 (pY705)', 'BANF1', 'TIM3', 'STING',
       'PAX8', 'HLA-DRA', 'HLA-DPB1', 'Goat IgG', 'NKG2D', 'H2AX',
       'pTBK1', 'NFKB', 'PROX1', 'PLCG2', 'CK20', 'GPC1', 'PDGFRa',
       'LamB2', 'Na/K ATPase', 'Histone H3 Phospho', 'ASMA',
       'Cytokeratin 7', 'Collagen 1', 'E Cadherin', 'Estrogen Receptor',
       'HH3', 'Nucleus', 'Tryptase', 'pS6', 'Donkey anti-Goat IgG-AF488',
       'MCM6', 'Na+/K+ ATPase alpha-1 subunit', 'CDX2',
       'Histone H3.1 (K27ac)', 'N-cadherin', 'Histone H2AX (pS139)',
       'S100-A1', 'IRF-1', '40S ribosomal protein S6 (pS235; pS236)',
       'Fibronectin', 'VEGFR-2', 'Trop2', 'TP63', 'gH2Ax', 'pSTAT3',
       'IBA1', 'NFP', 'ATRX', 'PAX5', 'ASCL1', 'APOE', 'S100B', 'OLIG1',
       'H3K27M', 'SOX4', 'P2RY12', 'PDGFRA', 'NeuN', 'MOG', 'SPP1',
       'FOSL1', 'TMEM119', 'OLIG2', 'Sox2', 'Chromogranin A', 'Rat-IgG',
       'Rabbit-IgG', 'Mouse-IgG', 'CDX-2', 'GranB', 'CK-20', 'CK-18',
       'CK-8', 'Tubulin alpha-1B chain', 'Sequestosome-1', 'AIF-1',
       'Tubulin beta chain', 'Paired box protein Pax-5',
       'Paired box protein Pax-8', 'RNA polymerase II subunit B1',
       'NFATc1', 'Phospho-BPK (Tyr551, Tyr511)', 'HHLA2', 'Chymase',
       'Stat1 (pY701)', 'Cleaved PARP (D214)', 'Snail1', 'S100 alpha',
       'LDH', 'Langerin', 'S6 (pS240; pS244)', 'CD40LG', 'c-Kit', 'CDH17',
       'CLDN4', 'PDX1', 'Synaptophysin', 'CDX1', 'PDGFRB', 'WNT2',
       'PDGFR-alpha', 'MCM2', 'CCNE1', 'CCNB1', 'GM130', 'Geminin',
       'COX4', 'BRD2', 'GLUD1', 'GAPDH', 'Histone H3.1 (pS10)', 'AREB6',
       'Sox4', 'HER3', 'Tbx21', 'Donkey anti-Goat IgG-AF555', 'MIF',
       'CCR7', 'anti human nuclear antigen', 'EPR4097', 'EPR7785', 'TERT',
       'NEURL1', 'PLIN4', 'NAKATAase', 'ICOS', 'HLA-DRB1', 'GITR',
       'Melan-A', 'c-Myc', 'NOS2', 'IFITM3', 'Interferon gamma', 'PMEL',
       'Sox10', 'IFI16', 'MART-1', 'MX1', 'IRF-4', 'IRF-5', 'IRF1',
       'SREBP-1', 'SMAD1', 'CPT1A', 'SMAD5', 'SMAD2', 'SMAD3', 'Bcl2',
       'EPR20129-217', 'Keratin', 'ki-67', 'NeuroD1', 'RRBP1', 'S100A12',
       'ARF', 'CDKN1A', 'p27 KIP1', 'p75 NGF', 'Hes1', 'CDKN2A', 'CCNA',
       'p57/Kip2', 'FN', 'c-Maf', 'HO-1', 'IFNB'], dtype=object)

In [26]:
# flip enhanced_metadata_df_enhanced to be centered around the extraced_marker and have extraced_marker, marker_type and thewn a list of the row_hashes and ch_synids associated with that marker
extracted_marker_centered_json = []
grouped = enhanced_metadata_df_enhanced.groupby(['extracted_marker', 'marker_type'])
for (marker, marker_type), group in grouped:
    entry = {
        'extracted_marker': marker,
        'marker_type': marker_type,
        'row_hashes': group['row_hash'].tolist(),
        'row_contents': group['row_content'].tolist(),
        'ch_synids': [synid for sublist in group['ch_synids'].tolist() for synid in sublist]
    }
    extracted_marker_centered_json.append(entry)

extracted_marker_centered_json[0:2]  # show first 2 entries

[{'extracted_marker': '40S ribosomal protein S6',
  'marker_type': 'protein_single',
  'row_hashes': ['0b9e8f26bace3264979ce5e5a4469a2e'],
  'row_contents': [{'Channel ID': 'Channel:0:14',
    'Channel Name': '40S ribosomal protein S6',
    'Channel Passed QC': 'Yes',
    'Cycle Number': 4,
    'Sub Cycle Number': nan,
    'Target Name': '40S ribosomal protein S6',
    'Antibody Name': nan,
    'Antibody Role': 'primary',
    'RRID identifier': 'AB_10828226',
    'Fluorophore': 'Alexa Fluor 555',
    'Clone': '54D2',
    'Lot': nan,
    'Vendor': 'Cell Signaling Technology',
    'Catalog Number': '6989S',
    'Excitation Wavelength': 555,
    'Emission Wavelength': 590,
    'Excitation Bandwidth': 20,
    'Emission Bandwidth': 20,
    'Metal Isotope Element': nan,
    'Metal Isotope Mass': nan,
    'Oligo Barcode Upper Strand': nan,
    'Oligo Barcode Lower Strand': nan,
    'Dilution': '1:200',
    'Concentration': nan}],
  'ch_synids': ['syn25509678']},
 {'extracted_marker': '40S ribosomal protein S6 (pS235; pS236)',
  'marker_type': 'protein_single',
  'row_hashes': ['a7f65392c21af205ccc1cb8b44b98e48'],
  'row_contents': [{'Channel ID': 'Channel:0:41',
    'Channel Name': '40S ribosomal protein S6 (pS235; pS236)',
    'Channel Passed QC': 'Yes',
    'Cycle Number': 11,
    'Sub Cycle Number': nan,
    'Target Name': '40S ribosomal protein S6 (pS235; pS236)',
    'Antibody Name': 'S6 Ribosomal Protein (pS235; pS236)-AF488',
    'Antibody Role': 'Primary',
    'RRID identifier': 'AB_916158',
    'Fluorophore': 'Alexa Fluor 488',
    'Clone': 'D57.2.2E',
    'Lot': nan,
    'Vendor': 'Cell Signaling Technology',
    'Catalog Number': '4803',
    'Excitation Wavelength': 485,
    'Emission Wavelength': 522,
    'Excitation Bandwidth': 25,
    'Emission Bandwidth': 20,
    'Metal Isotope Element': nan,
    'Metal Isotope Mass': nan,
    'Oligo Barcode Upper Strand': nan,
    'Oligo Barcode Lower Strand': nan,
    'Dilution': '1:200',
    'Concentration': nan}],
  'ch_synids': ['syn26643858', 'syn26720998']}]

In [27]:
# show an example with moe than one row hash
for entry in extracted_marker_centered_json:
    if len(entry['row_hashes']) > 1:
        print(entry)
        break

{'extracted_marker': '53BP1', 'marker_type': 'protein_single', 'row_hashes': ['ce21ca7ecf58d56f62f87b88dfcb5ad1', 'f54793dd5cb0fa907da1be6c9268c5c8'], 'row_contents': [{'ID': 'R3-5', 'Markers': '53BP1', 'Round': 3, 'Channel': 5, 'ExpTime': 400}, {'ID': 'R2-5', 'Markers': '53BP1', 'Round': 2, 'Channel': 5, 'ExpTime': 0}], 'ch_synids': ['syn52287352', 'syn52287355', 'syn52287382']}

In [28]:
# Simple Claude API call using uniprot_api as a tool
from anthropic import Anthropic
from uniprot_api import lookup_protein
import json

client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

# Define the tool schema for uniprot_api
tools = [
    {
        "name": "lookup_protein",
        "description": "Searches the UniProt database for protein information by gene name or protein name. Returns detailed protein entries including gene name, protein name, organism, subcellular location, function, and confidence score.",
        "input_schema": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "The gene name or protein name to search for (e.g., 'CD20', 'FOXP3', 'Ki67')"
                },
                "organism": {
                    "type": "string",
                    "description": "The organism to filter by (default: 'human')",
                    "default": "human"
                }
            },
            "required": ["query"]
        }
    }
]

# Make a Claude API call asking about a protein
user_message = "Can you look up information about the protein CD20 in humans?"

response = client.messages.create(
    model="claude-sonnet-4-5",
    max_tokens=1024,
    tools=tools,
    messages=[{"role": "user", "content": user_message}]
)

print("Claude's initial response:")
print(response)

# Check if Claude wants to use the tool
if response.stop_reason == "tool_use":
    # Extract the tool use request
    tool_use_block = next(block for block in response.content if block.type == "tool_use")
    
    print(f"\n🔧 Claude wants to call: {tool_use_block.name}")
    print(f"📝 With arguments: {tool_use_block.input}")
    
    # Execute the actual function
    query = tool_use_block.input["query"]
    organism = tool_use_block.input.get("organism", "human")
    
    print(f"\n🔍 Calling lookup_protein('{query}', '{organism}')...")
    results = lookup_protein(query, organism)
    
    # Format the results
    tool_result = {
        "results": [entry.to_dict() for entry in results]
    }
    
    print(f"✅ Found {len(results)} results")
    
    # Send the tool result back to Claude
    final_response = client.messages.create(
        model="claude-sonnet-4-5",
        max_tokens=1024,
        tools=tools,
        messages=[
            {"role": "user", "content": user_message},
            {"role": "assistant", "content": response.content},
            {
                "role": "user",
                "content": [
                    {
                        "type": "tool_result",
                        "tool_use_id": tool_use_block.id,
                        "content": json.dumps(tool_result)
                    }
                ]
            }
        ]
    )
    
    print("\n📊 Claude's final response:")
    print(final_response.content[0].text)

Claude's initial response:
Message(id='msg_01R7zddLoejVgBinXzjFpDi4', content=[ToolUseBlock(id='toolu_01WteYHvizCjRB7MZKb7QP5Q', input={'query': 'CD20', 'organism': 'human'}, name='lookup_protein', type='tool_use')], model='claude-sonnet-4-5-20250929', role='assistant', stop_reason='tool_use', stop_sequence=None, type='message', usage=Usage(cache_creation=CacheCreation(ephemeral_1h_input_tokens=0, ephemeral_5m_input_tokens=0), cache_creation_input_tokens=0, cache_read_input_tokens=0, input_tokens=674, output_tokens=71, server_tool_use=None, service_tier='standard'))

🔧 Claude wants to call: lookup_protein
📝 With arguments: {'query': 'CD20', 'organism': 'human'}

🔍 Calling lookup_protein('CD20', 'human')...
✅ Found 10 results

📊 Claude's final response:
Based on the search results, I found information about **CD20** in humans:

## Primary Match: B-lymphocyte antigen CD20

**Gene Name:** MS4A1
**Accession:** P11836
**Organism:** Homo sapiens (Human)

### Subcellular Location:
- Cell membrane

### Function:
CD20 is a B-lymphocyte-specific membrane protein that plays a critical role in the regulation of cellular calcium influx, which is necessary for the:
- Development of B-lymphocytes
- Differentiation of B-lymphocytes
- Activation of B-lymphocytes

**Mechanism:** CD20 functions as a store-operated calcium (SOC) channel component that promotes calcium influx after activation by the B-cell receptor (BCR).

### Clinical Significance:
CD20 is one of the most important biomarkers in immunology and hematology. It's widely used as a target for therapeutic monoclonal antibodies (like rituximab) in the treatment of B-cell lymphomas and autoimmune diseases, since it's specifically expressed on B-cells from early development through maturity (but not on plasma cells).

In [ ]:
# Intelligent Claude-based UniProt lookup with metadata context
from anthropic import Anthropic, transform_schema
from uniprot_api import lookup_protein
import json

client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

# simple schema with uniprot id and subcellular location
#   where subcellular_location is one off cytoplasm, nucleus, cell memberane, extracellular.
class SubcellularLocationEnum(str, Enum):
    cytoplasm = "cytoplasm"
    nucleus = "nucleus"
    cell_membrane = "cell_membrane"
    extracellular = "extracellular"

class UniprotOutputSchema(BaseModel):
    accession: str = Field(..., description="The UniProt accession ID of the protein.")
    gene_name: str = Field(..., description="The gene name associated with the protein.")
    protein_name: str = Field(..., description="The full name of the protein.")
    organism: str = Field(..., description="The organism from which the protein is derived.")
    subcellular_location: SubcellularLocationEnum = Field(..., description="List of subcellular locations where the protein is found.")
    #function: str = Field(..., description="A brief description of the protein's function.")
    confidence_score: float = Field(..., description="Confidence score of the protein match (0 to 1).")
    
# Define the tool - Claude calls this to search UniProt
tools = [
    {
        "name": "lookup_protein",
        "description": "Searches the UniProt database for protein information by gene name or protein name. Returns a list of matching protein entries with details like gene name, protein name, organism, subcellular location, function, and confidence score. Use this to find candidate proteins that match the marker.",
        "input_schema": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "The gene name or protein name to search for (e.g., 'CD20', 'FOXP3', 'Ki67')"
                },
                "organism": {
                    "type": "string",
                    "description": "The organism to filter by (default: 'human')",
                    "default": "human"
                }
            },
            "required": ["query"]
        }
    }
]

def curate_marker_with_claude(marker_entry):
    """
    Use Claude to intelligently curate a marker by:
    1. Looking up the marker in UniProt
    2. Using ALL the metadata context to select the best match
    3. Returning the selected UniProt entry with reasoning
    """
    
    extracted_marker = marker_entry['extracted_marker']
    marker_type = marker_entry['marker_type']
    row_contents = marker_entry['row_contents']
    
    # Build a rich prompt with ALL context
    user_message = f"""I need you to find the correct UniProt entry for this antibody marker used in imaging:

**Extracted Marker**: {extracted_marker}
**Marker Type**: {marker_type}

**Imaging Metadata** (use this context to select the right protein):
{json.dumps(row_contents, indent=2)}

Please:
1. Search UniProt for "{extracted_marker}"
2. Review all the results you find
3. Use the imaging metadata (antibody clone, vendor, catalog number, target name, etc.) to determine which UniProt entry is the correct match
4. If there are multiple good matches, explain why you chose one
5. If the metadata suggests this isn't actually a protein (e.g., it's a control antibody, isotype control, or chemical stain), note that

Return your analysis with:
- The selected UniProt accession and gene name
- Your confidence level (high/medium/low)
- Your reasoning for the selection"""

    # Initial call - Claude decides to use the tool
    response = client.messages.create(
        model="claude-sonnet-4-5",
        max_tokens=4096,
        tools=tools,
        messages=[{"role": "user", "content": user_message}]
    )
    
    # Check if Claude wants to use the tool
    if response.stop_reason == "tool_use":
        tool_use_block = next(block for block in response.content if block.type == "tool_use")
        
        # Execute the UniProt lookup
        query = tool_use_block.input["query"]
        organism = tool_use_block.input.get("organism", "human")
        results = lookup_protein(query, organism)
        
        # Format results for Claude
        tool_result_text = f"Found {len(results)} UniProt entries for '{query}':\n\n"
        for i, entry in enumerate(results, 1):
            tool_result_text += f"Result {i}:\n"
            tool_result_text += f"  Accession: {entry.accession}\n"
            tool_result_text += f"  Gene: {entry.gene_name}\n"
            tool_result_text += f"  Protein: {entry.protein_name}\n"
            tool_result_text += f"  Organism: {entry.organism}\n"
            tool_result_text += f"  Confidence: {entry.confidence_score}\n"
            if entry.subcellular_location:
                tool_result_text += f"  Location: {', '.join(entry.subcellular_location)}\n"
            if entry.function:
                tool_result_text += f"  Function: {entry.function[:300]}...\n"
            tool_result_text += "\n"
        
        # Continue conversation with tool results
        messages = [
            {"role": "user", "content": user_message},
            {"role": "assistant", "content": [
                {
                    "type": "tool_use",
                    "id": tool_use_block.id,
                    "name": tool_use_block.name,
                    "input": tool_use_block.input
                }
            ]},
            {
                "role": "user",
                "content": [
                    {
                        "type": "tool_result",
                        "tool_use_id": tool_use_block.id,
                        "content": tool_result_text
                    }
                ]
            }
        ]
        
        # Get Claude's analysis
        final_response = client.beta.messages.create(
            model="claude-sonnet-4-5",
            betas =["structured-outputs-2025-11-13"],
            max_tokens=4096,
            tools=tools,
            messages=messages,
            output_format={ 
                    "type": "json_schema", 
                    "schema": transform_schema(UniprotOutputSchema)
            }
        )
        
        return {
            'extracted_marker': extracted_marker,
            'marker_type': marker_type,
            #'uniprot_results_count': len(results),
            'uniprot_summary': final_response.content[0].text,
            #'all_uniprot_results': [r.to_dict() for r in results]
        }
    
    else:
        # Claude responded without using tools
        return {
            'extracted_marker': extracted_marker,
            'marker_type': marker_type,
            'claude_response': response.content[0].text
        }


# Test with a real example from your data
# First, let's restructure your data to include row_contents for each unique marker
def prepare_marker_entries(df):
    """Group by extracted_marker and collect all associated metadata"""
    marker_entries = []
    
    for marker in df['extracted_marker'].unique():
        if pd.isna(marker) or marker in ['blank', 'Empty', 'Blank', '9999']:
            continue
            
        marker_rows = df[df['extracted_marker'] == marker]
        marker_type = marker_rows.iloc[0]['marker_type']
        
        # Collect all row contents for this marker
        row_contents = []
        row_hashes = []
        ch_synids = []
        
        for _, row in marker_rows.iterrows():
            row_contents.append(row['row_content'])
            row_hashes.append(row['row_hash'])
            ch_synids.extend(row['ch_synids'])
        
        marker_entries.append({
            'extracted_marker': marker,
            'marker_type': marker_type,
            'row_hashes': row_hashes,
            'row_contents': row_contents,
            'ch_synids': list(set(ch_synids))
        })
    
    return marker_entries

# Test with one marker
print("Preparing marker entries...")
marker_entries = prepare_marker_entries(enhanced_metadata_df_enhanced)
print(f"Found {len(marker_entries)} unique markers to curate")

# Test with CD20
cd20_entry = [m for m in marker_entries if m['extracted_marker'] == 'CD20'][0]
print(f"\nTesting with CD20 marker...")
print(f"  Marker type: {cd20_entry['marker_type']}")
print(f"  Number of metadata rows: {len(cd20_entry['row_contents'])}")
print(f"  Number of synapse IDs: {len(cd20_entry['ch_synids'])}")

result = curate_marker_with_claude(cd20_entry)

print("\n" + "="*80)
print("CLAUDE'S ANALYSIS")
print("="*80)
print(result)

Preparing marker entries...
Found 821 unique markers to curate

Testing with CD20 marker...
  Marker type: cd_marker
  Number of metadata rows: 84
  Number of synapse IDs: 514

================================================================================
CLAUDE'S ANALYSIS
================================================================================
{'extracted_marker': 'CD20', 'marker_type': 'cd_marker', 'uniprot_summary': '{"accession": "P11836", "gene_name": "MS4A1", "protein_name": "B-lymphocyte antigen CD20", "organism": "Homo sapiens", "subcellular_location": "cell_membrane", "confidence_score": 1.0}'}

In [30]:
# sample 5 rows from protein_single marker type
protein_single_entries = [m for m in marker_entries if m['marker_type'] == 'protein_single']
sampled_entries = random.sample(protein_single_entries, 5)

for entry in sampled_entries:
    print(f"\nCurating marker: {entry['extracted_marker']} ({len(entry['row_contents'])} metadata rows)")
    
    result = curate_marker_with_claude(entry)
    print(result['uniprot_summary'])

Curating marker: Cytokeratin 14 (1 metadata rows)
 {"accession": "P02533", "gene_name": "KRT14", "protein_name": "Keratin, type I cytoskeletal 14", "organism": "Homo sapiens", "subcellular_location": "cytoplasm", "confidence_score": 0.95}

Curating marker: MART-1 (2 metadata rows)
{"accession": "Q16655", "gene_name": "MLANA", "protein_name": "Melanoma antigen recognized by T-cells 1", "organism": "Homo sapiens", "subcellular_location": "cell_membrane", "confidence_score": 0.95}

Curating marker: cGAS (4 metadata rows)

KeyboardInterrupt:

In [44]:
for entry in protein_single_entries:
    uniprot_results = lookup_protein(entry['extracted_marker'], organism='human')
    print(f"\nMarker: {entry['extracted_marker']} - Found {len(uniprot_results)} UniProt entries")
    # print top highest confidence score hit
    if uniprot_results:
        top_hit = max(uniprot_results, key=lambda x: x.confidence_score)
        print(f"  Top Hit: {top_hit.accession} | Gene: {top_hit.gene_name} | Protein: {top_hit.protein_name} | Confidence: {top_hit.confidence_score}")

Marker: Alpha-actinin 4 - Found 10 UniProt entries
  Top Hit: O43707 | Gene: ACTN4 | Protein: Alpha-actinin-4 | Confidence: 0.6

Marker: Beta-Catenin - Found 10 UniProt entries
  Top Hit: P35222 | Gene: CTNNB1 | Protein: Catenin beta-1 | Confidence: 0.6

Marker: CgA - Found 10 UniProt entries
  Top Hit: P01215 | Gene: CGA | Protein: Glycoprotein hormones alpha chain | Confidence: 1.0

Marker: Collagen - Found 10 UniProt entries
  Top Hit: Q02388 | Gene: COL7A1 | Protein: Collagen alpha-1(VII) chain | Confidence: 0.6

Marker: ERBB2 - Found 10 UniProt entries
  Top Hit: P04626 | Gene: ERBB2 | Protein: Receptor tyrosine-protein kinase erbB-2 | Confidence: 1.0

Marker: FOXP3 - Found 10 UniProt entries
  Top Hit: Q9BZS1 | Gene: FOXP3 | Protein: Forkhead box protein P3 | Confidence: 1.0

Marker: Gamma-Actin - Found 10 UniProt entries
  Top Hit: P63267 | Gene: ACTG2 | Protein: Actin, gamma-enteric smooth muscle | Confidence: 0.6

Marker: HLA-A - Found 10 UniProt entries
  Top Hit: P04439 | Gene: HLA-A | Protein: HLA class I histocompatibility antigen, A alpha chain | Confidence: 1.0

Marker: Lysozyme - Found 10 UniProt entries
  Top Hit: P61626 | Gene: LYZ | Protein: Lysozyme C | Confidence: 0.6

Marker: Muc2 - Found 10 UniProt entries
  Top Hit: Q02817 | Gene: MUC2 | Protein: Mucin-2 | Confidence: 1.0

Marker: NaKATPase - Found 9 UniProt entries
  Top Hit: Q4VNC1 | Gene: ATP13A4 | Protein: Probable cation-transporting ATPase 13A4 | Confidence: 0.6

Marker: OLFM4 - Found 10 UniProt entries
  Top Hit: Q6UX06 | Gene: OLFM4 | Protein: Olfactomedin-4 | Confidence: 1.0

Marker: PCNA - Found 10 UniProt entries
  Top Hit: P12004 | Gene: PCNA | Protein: Proliferating cell nuclear antigen | Confidence: 1.0

Marker: pEGFR - Found 0 UniProt entries

Marker: p-STAT3 - Found 10 UniProt entries
  Top Hit: P40763 | Gene: STAT3 | Protein: Signal transducer and activator of transcription 3 | Confidence: 0.7999999999999999

Marker: SMA - Found 10 UniProt entries
  Top Hit: O43541 | Gene: SMAD6 | Protein: Mothers against decapentaplegic homolog 6 | Confidence: 0.7999999999999999

Marker: Sox9 - Found 10 UniProt entries
  Top Hit: P48436 | Gene: SOX9 | Protein: Transcription factor SOX-9 | Confidence: 1.0

Marker: Vimentin - Found 10 UniProt entries
  Top Hit: P08670 | Gene: VIM | Protein: Vimentin | Confidence: 0.7999999999999999

Marker: PDL1 - Found 4 UniProt entries
  Top Hit: Q9NZQ7 | Gene: CD274 | Protein: Programmed cell death 1 ligand 1 | Confidence: 0.6

Marker: EOMES - Found 7 UniProt entries
  Top Hit: O95936 | Gene: EOMES | Protein: Eomesodermin homolog | Confidence: 1.0

Marker: DC-LAMP - Found 1 UniProt entries
  Top Hit: Q9UQV4 | Gene: LAMP3 | Protein: Lysosome-associated membrane glycoprotein 3 | Confidence: 0.6

Marker: GrzB - Found 0 UniProt entries

Marker: T-bet - Found 10 UniProt entries
  Top Hit: Q9UL17 | Gene: TBX21 | Protein: T-box transcription factor TBX21 | Confidence: 0.6

Marker: Foxp3 - Found 10 UniProt entries
  Top Hit: Q9BZS1 | Gene: FOXP3 | Protein: Forkhead box protein P3 | Confidence: 1.0

Marker: Ki67 - Found 5 UniProt entries
  Top Hit: P46013 | Gene: MKI67 | Protein: Proliferation marker protein Ki-67 | Confidence: 0.7999999999999999

Marker: SMOC2 - Found 2 UniProt entries
  Top Hit: Q9H3U7 | Gene: SMOC2 | Protein: SPARC-related modular calcium-binding protein 2 | Confidence: 1.0

Marker: BMX - Found 10 UniProt entries
  Top Hit: P51813 | Gene: BMX | Protein: Cytoplasmic tyrosine-protein kinase BMX | Confidence: 1.0

Marker: Alpha-SMA - Found 7 UniProt entries
  Top Hit: Q9UEY8 | Gene: ADD3 | Protein: Gamma-adducin | Confidence: 0.6

Marker: MUC2 - Found 10 UniProt entries
  Top Hit: Q02817 | Gene: MUC2 | Protein: Mucin-2 | Confidence: 1.0

Marker: MKi67 - Found 10 UniProt entries
  Top Hit: P46013 | Gene: MKI67 | Protein: Proliferation marker protein Ki-67 | Confidence: 1.0

Marker: AGR2 - Found 10 UniProt entries
  Top Hit: O95994 | Gene: AGR2 | Protein: Anterior gradient protein 2 homolog | Confidence: 1.0

Marker: IGLL5 - Found 1 UniProt entries
  Top Hit: B9A064 | Gene: IGLL5 | Protein: Immunoglobulin lambda-like polypeptide 5 | Confidence: 1.0

Marker: CHGA - Found 7 UniProt entries
  Top Hit: P10645 | Gene: CHGA | Protein: Chromogranin-A | Confidence: 1.0

Marker: MYH11 - Found 5 UniProt entries
  Top Hit: P35749 | Gene: MYH11 | Protein: Myosin-11 | Confidence: 1.0

Marker: SYNAPTOPHYSIN - Found 10 UniProt entries
  Top Hit: P08247 | Gene: SYP | Protein: Synaptophysin | Confidence: 0.6

Marker: KRT18 - Found 10 UniProt entries
  Top Hit: P05783 | Gene: KRT18 | Protein: Keratin, type I cytoskeletal 18 | Confidence: 1.0

Marker: PDPN - Found 10 UniProt entries
  Top Hit: Q86YL7 | Gene: PDPN | Protein: Podoplanin | Confidence: 1.0

Marker: CTNNA2 - Found 5 UniProt entries
  Top Hit: P26232 | Gene: CTNNA2 | Protein: Catenin alpha-2 | Confidence: 1.0

Marker: WNT2B - Found 5 UniProt entries
  Top Hit: Q93097 | Gene: WNT2B | Protein: Protein Wnt-2b | Confidence: 1.0

Marker: WNT5B - Found 3 UniProt entries
  Top Hit: Q9H1J7 | Gene: WNT5B | Protein: Protein Wnt-5b | Confidence: 1.0

Marker: RSPO3 - Found 10 UniProt entries
  Top Hit: Q9BXY4 | Gene: RSPO3 | Protein: R-spondin-3 | Confidence: 1.0

Marker: Cox2 - Found 10 UniProt entries
  Top Hit: Q5RI15 | Gene: COX20 | Protein: Cytochrome c oxidase assembly protein COX20, mitochondrial | Confidence: 0.7999999999999999

Marker: ACTG1 - Found 10 UniProt entries
  Top Hit: P63261 | Gene: ACTG1 | Protein: Actin, cytoplasmic 2 | Confidence: 1.0

Marker: MUC5AC - Found 10 UniProt entries
  Top Hit: P98088 | Gene: MUC5AC | Protein: Mucin-5AC | Confidence: 1.0

Marker: Na/K-ATPase - Found 10 UniProt entries
  Top Hit: P13637 | Gene: ATP1A3 | Protein: Sodium/potassium-transporting ATPase subunit alpha-3 | Confidence: 0.6

Marker: AQP5 - Found 10 UniProt entries
  Top Hit: P55064 | Gene: AQP5 | Protein: Aquaporin-5 | Confidence: 1.0

Marker: Podoplanin - Found 9 UniProt entries
  Top Hit: Q86YL7 | Gene: PDPN | Protein: Podoplanin | Confidence: 0.6

Marker: Hepatocyte Paraffin 1 - Found 0 UniProt entries

Marker: GLUT1 - Found 10 UniProt entries
  Top Hit: P11166 | Gene: SLC2A1 | Protein: Solute carrier family 2, facilitated glucose transporter member 1 | Confidence: 0.6

Marker: CK19 - Found 0 UniProt entries

Marker: E-cadherin - Found 10 UniProt entries
  Top Hit: P12830 | Gene: CDH1 | Protein: Cadherin-1 | Confidence: 0.6

Marker: MUC-2 - Found 5 UniProt entries
  Top Hit: Q02817 | Gene: MUC2 | Protein: Mucin-2 | Confidence: 0.6

Marker: SOX9 - Found 10 UniProt entries
  Top Hit: P48436 | Gene: SOX9 | Protein: Transcription factor SOX-9 | Confidence: 1.0

Marker: FoxP3 - Found 10 UniProt entries
  Top Hit: Q9BZS1 | Gene: FOXP3 | Protein: Forkhead box protein P3 | Confidence: 1.0

Marker: P21 - Found 10 UniProt entries
  Top Hit: Q9H633 | Gene: RPP21 | Protein: Ribonuclease P protein subunit p21 | Confidence: 0.7999999999999999

Marker: CK7 - Found 2 UniProt entries
  Top Hit: Q02833 | Gene: RASSF7 | Protein: Ras association domain-containing protein 7 | Confidence: 0.6

Marker: P16 - Found 10 UniProt entries
  Top Hit: P09467 | Gene: FBP1 | Protein: Fructose-1,6-bisphosphatase 1 | Confidence: 0.6

Marker: CCL2 - Found 10 UniProt entries
  Top Hit: P13500 | Gene: CCL2 | Protein: C-C motif chemokine 2 | Confidence: 1.0

Marker: PAI1 - Found 10 UniProt entries
  Top Hit: P05121 | Gene: SERPINE1 | Protein: Plasminogen activator inhibitor 1 | Confidence: 0.6

Marker: COL6A2 - Found 4 UniProt entries
  Top Hit: P12110 | Gene: COL6A2 | Protein: Collagen alpha-2(VI) chain | Confidence: 1.0

Marker: ALPHA-SMA - Found 7 UniProt entries
  Top Hit: Q9UEY8 | Gene: ADD3 | Protein: Gamma-adducin | Confidence: 0.6

Marker: CEA - Found 10 UniProt entries
  Top Hit: Q2WEN9 | Gene: CEACAM16 | Protein: Cell adhesion molecule CEACAM16 | Confidence: 0.7999999999999999

Marker: VIMENTIN - Found 10 UniProt entries
  Top Hit: P08670 | Gene: VIM | Protein: Vimentin | Confidence: 0.7999999999999999

Marker: SLC19A2 - Found 4 UniProt entries
  Top Hit: O60779 | Gene: SLC19A2 | Protein: Thiamine transporter 1 | Confidence: 1.0

Marker: RUNX1 - Found 10 UniProt entries
  Top Hit: Q01196 | Gene: RUNX1 | Protein: Runt-related transcription factor 1 | Confidence: 1.0

Marker: VCAN - Found 5 UniProt entries
  Top Hit: P13611 | Gene: VCAN | Protein: Versican core protein | Confidence: 1.0

Marker: SOX2 - Found 10 UniProt entries
  Top Hit: P48431 | Gene: SOX2 | Protein: Transcription factor SOX-2 | Confidence: 1.0

Marker: MUC1 - Found 10 UniProt entries
  Top Hit: P15941 | Gene: MUC1 | Protein: Mucin-1 | Confidence: 1.0

Marker: Beta-catenin - Found 10 UniProt entries
  Top Hit: P35222 | Gene: CTNNB1 | Protein: Catenin beta-1 | Confidence: 0.6

Marker: GLUT (D) - Found 10 UniProt entries
  Top Hit: P14672 | Gene: SLC2A4 | Protein: Solute carrier family 2, facilitated glucose transporter member 4 | Confidence: 0.6

Marker: Keratin 14 - Found 10 UniProt entries
  Top Hit: P02533 | Gene: KRT14 | Protein: Keratin, type I cytoskeletal 14 | Confidence: 0.6

Marker: PAI - Found 10 UniProt entries
  Top Hit: Q9ULR5 | Gene: PAIP2B | Protein: Polyadenylate-binding protein-interacting protein 2B | Confidence: 0.7999999999999999

Marker: DPEP1 - Found 6 UniProt entries
  Top Hit: P16444 | Gene: DPEP1 | Protein: Dipeptidase 1 | Confidence: 1.0

Marker: CEACAM5 - Found 3 UniProt entries
  Top Hit: P06731 | Gene: CEACAM5 | Protein: Cell adhesion molecule CEACAM5 | Confidence: 1.0

Marker: PD-L1 - Found 10 UniProt entries
  Top Hit: Q9NZQ7 | Gene: CD274 | Protein: Programmed cell death 1 ligand 1 | Confidence: 0.6

Marker: LAG3 - Found 4 UniProt entries
  Top Hit: P18627 | Gene: LAG3 | Protein: Lymphocyte activation gene 3 protein | Confidence: 1.0

Marker: Granzyme B - Found 10 UniProt entries
  Top Hit: O95155 | Gene: UBE4B | Protein: Ubiquitin conjugation factor E4 B | Confidence: 0.6

Marker: PD-L2 - Found 2 UniProt entries
  Top Hit: Q9BQ51 | Gene: PDCD1LG2 | Protein: Programmed cell death 1 ligand 2 | Confidence: 0.6

Marker: Histone H3 - Found 10 UniProt entries
  Top Hit: Q6NXT2 | Gene: H3-5 | Protein: Histone H3.3C | Confidence: 0.6

Marker: Vimentine - Found 0 UniProt entries

Marker: GLUT - Found 10 UniProt entries
  Top Hit: P14672 | Gene: SLC2A4 | Protein: Solute carrier family 2, facilitated glucose transporter member 4 | Confidence: 0.6

Marker: HER2 - Found 10 UniProt entries
  Top Hit: P04626 | Gene: ERBB2 | Protein: Receptor tyrosine-protein kinase erbB-2 | Confidence: 0.6

Marker: ER - Found 10 UniProt entries
  Top Hit: P30040 | Gene: ERP29 | Protein: Endoplasmic reticulum resident protein 29 | Confidence: 0.7999999999999999

Marker: pHH3 - Found 0 UniProt entries

Marker: CK14 - Found 3 UniProt entries
  Top Hit: Q8N8R7 | Gene: ARL14EP | Protein: ARL14 effector protein | Confidence: 0.6

Marker: CK5 - Found 8 UniProt entries
  Top Hit: Q96SN8 | Gene: CDK5RAP2 | Protein: CDK5 regulatory subunit-associated protein 2 | Confidence: 0.6

Marker: LamAC - Found 0 UniProt entries

Marker: aSMA - Found 0 UniProt entries

Marker: EP700Y - Found 0 UniProt entries

Marker: CK17 - Found 1 UniProt entries
  Top Hit: Q9NQ31 | Gene: AKIP1 | Protein: A-kinase-interacting protein 1 | Confidence: 0.6

Marker: Hep-Par-1 - Found 0 UniProt entries

Marker: OTOP3 - Found 8 UniProt entries
  Top Hit: Q7RTS5 | Gene: OTOP3 | Protein: Proton channel OTOP3 | Confidence: 1.0

Marker: REG4 - Found 1 UniProt entries
  Top Hit: Q9BYZ8 | Gene: REG4 | Protein: Regenerating islet-derived protein 4 | Confidence: 1.0

Marker: RETNLB - Found 1 UniProt entries
  Top Hit: Q9BQ08 | Gene: RETNLB | Protein: Resistin-like beta | Confidence: 1.0

Marker: SOX17 - Found 5 UniProt entries
  Top Hit: Q9H6I2 | Gene: SOX17 | Protein: Transcription factor SOX-17 | Confidence: 1.0

Marker: NOVA2 - Found 3 UniProt entries
  Top Hit: Q9UNW9 | Gene: NOVA2 | Protein: RNA-binding protein Nova-2 | Confidence: 1.0

Marker: HNF4A - Found 10 UniProt entries
  Top Hit: P41235 | Gene: HNF4A | Protein: Hepatocyte nuclear factor 4-alpha | Confidence: 1.0

Marker: KRT20 - Found 10 UniProt entries
  Top Hit: P35900 | Gene: KRT20 | Protein: Keratin, type I cytoskeletal 20 | Confidence: 1.0

Marker: COX2/PTGS2 - Found 5 UniProt entries
  Top Hit: P35354 | Gene: PTGS2 | Protein: Prostaglandin G/H synthase 2 | Confidence: 0.7999999999999999

Marker: ATP1B1 - Found 10 UniProt entries
  Top Hit: P05026 | Gene: ATP1B1 | Protein: Sodium/potassium-transporting ATPase subunit beta-1 | Confidence: 1.0

Marker: COL6A1 - Found 3 UniProt entries
  Top Hit: P12109 | Gene: COL6A1 | Protein: Collagen alpha-1(VI) chain | Confidence: 1.0

Marker: BACH1 - Found 10 UniProt entries
  Top Hit: O14867 | Gene: BACH1 | Protein: Transcription regulator protein BACH1 | Confidence: 1.0

Marker: SMARCC1 - Found 10 UniProt entries
  Top Hit: Q92922 | Gene: SMARCC1 | Protein: SWI/SNF complex subunit SMARCC1 | Confidence: 1.0

Marker: PBX3 - Found 10 UniProt entries
  Top Hit: P40426 | Gene: PBX3 | Protein: Pre-B-cell leukemia transcription factor 3 | Confidence: 1.0

Marker: ASCL2 - Found 3 UniProt entries
  Top Hit: Q99929 | Gene: ASCL2 | Protein: Achaete-scute homolog 2 | Confidence: 1.0

Marker: CLDN1 - Found 10 UniProt entries
  Top Hit: O95832 | Gene: CLDN1 | Protein: Claudin-1 | Confidence: 1.0

Marker: Mki67 - Found 10 UniProt entries
  Top Hit: P46013 | Gene: MKI67 | Protein: Proliferation marker protein Ki-67 | Confidence: 1.0

Marker: BEST4 - Found 1 UniProt entries
  Top Hit: Q8NFU0 | Gene: BEST4 | Protein: Bestrophin-4 | Confidence: 1.0

Marker: DC_LAMP - Found 1 UniProt entries
  Top Hit: Q9UQV4 | Gene: LAMP3 | Protein: Lysosome-associated membrane glycoprotein 3 | Confidence: 0.6

Marker: HepPar1 - Found 0 UniProt entries

Marker: Alpha-actinin4 - Found 0 UniProt entries

Marker: DCLAMP - Found 1 UniProt entries
  Top Hit: Q9UQV4 | Gene: LAMP3 | Protein: Lysosome-associated membrane glycoprotein 3 | Confidence: 0.6

Marker: GRZB - Found 0 UniProt entries

Marker: TBET - Found 1 UniProt entries
  Top Hit: Q9UL17 | Gene: TBX21 | Protein: T-box transcription factor TBX21 | Confidence: 0.6

Marker: KI67 - Found 5 UniProt entries
  Top Hit: P46013 | Gene: MKI67 | Protein: Proliferation marker protein Ki-67 | Confidence: 0.7999999999999999

Marker: alpha SMA - Found 10 UniProt entries
  Top Hit: O15198 | Gene: SMAD9 | Protein: Mothers against decapentaplegic homolog 9 | Confidence: 0.6

Marker: AR - Found 10 UniProt entries
  Top Hit: P10275 | Gene: AR | Protein: Androgen receptor | Confidence: 1.0

Marker: BCA1 - Found 3 UniProt entries
  Top Hit: P56945 | Gene: BCAR1 | Protein: Breast cancer anti-estrogen resistance protein 1 | Confidence: 0.6

Marker: LYVE1 - Found 10 UniProt entries
  Top Hit: Q9Y5Y7 | Gene: LYVE1 | Protein: Lymphatic vessel endothelial hyaluronic acid receptor 1 | Confidence: 1.0

Marker: Aqp2 - Found 10 UniProt entries
  Top Hit: P41181 | Gene: AQP2 | Protein: Aquaporin-2 | Confidence: 1.0

Marker: Vim - Found 10 UniProt entries
  Top Hit: P08670 | Gene: VIM | Protein: Vimentin | Confidence: 1.0

Marker: LRP2 - Found 10 UniProt entries
  Top Hit: P98164 | Gene: LRP2 | Protein: Low-density lipoprotein receptor-related protein 2 | Confidence: 1.0

Marker: UMOD - Found 7 UniProt entries
  Top Hit: P07911 | Gene: UMOD | Protein: Uromodulin | Confidence: 1.0

Marker: CALB1 - Found 7 UniProt entries
  Top Hit: P05937 | Gene: CALB1 | Protein: Calbindin | Confidence: 1.0

Marker: AQP1 - Found 10 UniProt entries
  Top Hit: P29972 | Gene: AQP1 | Protein: Aquaporin-1 | Confidence: 1.0

Marker: CA9 - Found 8 UniProt entries
  Top Hit: Q16790 | Gene: CA9 | Protein: Carbonic anhydrase 9 | Confidence: 1.0

Marker: UCHL1 - Found 10 UniProt entries
  Top Hit: P09936 | Gene: UCHL1 | Protein: Ubiquitin carboxyl-terminal hydrolase isozyme L1 | Confidence: 1.0

Marker: BAP1 - Found 10 UniProt entries
  Top Hit: Q92560 | Gene: BAP1 | Protein: Ubiquitin carboxyl-terminal hydrolase BAP1 | Confidence: 1.0

Marker: Tbet - Found 1 UniProt entries
  Top Hit: Q9UL17 | Gene: TBX21 | Protein: T-box transcription factor TBX21 | Confidence: 0.6

Marker: BMI1 - Found 10 UniProt entries
  Top Hit: P35226 | Gene: BMI1 | Protein: Polycomb complex protein BMI-1 | Confidence: 1.0

Marker: RAB6B - Found 10 UniProt entries
  Top Hit: Q9NRW1 | Gene: RAB6B | Protein: Ras-related protein Rab-6B | Confidence: 1.0

Marker: PDE3A - Found 5 UniProt entries
  Top Hit: Q14432 | Gene: PDE3A | Protein: cGMP-inhibited 3',5'-cyclic phosphodiesterase 3A | Confidence: 1.0

Marker: SSR4 - Found 2 UniProt entries
  Top Hit: P51571 | Gene: SSR4 | Protein: Translocon-associated protein subunit delta | Confidence: 1.0

Marker: LGR5 - Found 10 UniProt entries
  Top Hit: O75473 | Gene: LGR5 | Protein: Leucine-rich repeat-containing G-protein coupled receptor 5 | Confidence: 1.0

Marker: S100 - Found 10 UniProt entries
  Top Hit: Q8WXG8 | Gene: S100Z | Protein: Protein S100-Z | Confidence: 0.7999999999999999

Marker: PDL-1 - Found 4 UniProt entries
  Top Hit: Q9NZQ7 | Gene: CD274 | Protein: Programmed cell death 1 ligand 1 | Confidence: 0.6

Marker: Her2 - Found 10 UniProt entries
  Top Hit: P04626 | Gene: ERBB2 | Protein: Receptor tyrosine-protein kinase erbB-2 | Confidence: 0.6

Marker: GATA3 - Found 10 UniProt entries
  Top Hit: P23771 | Gene: GATA3 | Protein: Trans-acting T-cell-specific transcription factor GATA-3 | Confidence: 1.0

Marker: TFF1 - Found 10 UniProt entries
  Top Hit: P04155 | Gene: TFF1 | Protein: Trefoil factor 1 | Confidence: 1.0

Marker: MGP - Found 6 UniProt entries
  Top Hit: P08493 | Gene: MGP | Protein: Matrix Gla protein | Confidence: 1.0

Marker: a-Amylase - Found 10 UniProt entries
  Top Hit: P0DUB6 | Gene: AMY1A | Protein: Alpha-amylase 1A | Confidence: 0.6

Marker: PR-(D) - Found 10 UniProt entries
  Top Hit: P86480 | Gene: PRR20D | Protein: Proline-rich protein 20D | Confidence: 0.6

Marker: Bap1 - Found 10 UniProt entries
  Top Hit: Q92560 | Gene: BAP1 | Protein: Ubiquitin carboxyl-terminal hydrolase BAP1 | Confidence: 1.0

Marker: COX6c - Found 10 UniProt entries
  Top Hit: P09669 | Gene: COX6C | Protein: Cytochrome c oxidase subunit 6C | Confidence: 1.0

Marker: PLAT/tPA - Found 4 UniProt entries
  Top Hit: P00750 | Gene: PLAT | Protein: Tissue-type plasminogen activator | Confidence: 0.7999999999999999

Marker: CTLA4 - Found 10 UniProt entries
  Top Hit: P16410 | Gene: CTLA4 | Protein: Cytotoxic T-lymphocyte protein 4 | Confidence: 1.0

Marker: SLC39A6 - Found 8 UniProt entries
  Top Hit: Q13433 | Gene: SLC39A6 | Protein: Zinc transporter ZIP6 | Confidence: 1.0

Marker: Keratin 5 - Found 10 UniProt entries
  Top Hit: P02533 | Gene: KRT14 | Protein: Keratin, type I cytoskeletal 14 | Confidence: 0.6

Marker: GZMB - Found 7 UniProt entries
  Top Hit: P10144 | Gene: GZMB | Protein: Granzyme B | Confidence: 1.0

Marker: Mouse IgG - Found 10 UniProt entries
  Top Hit: O14836 | Gene: TNFRSF13B | Protein: Tumor necrosis factor receptor superfamily member 13B | Confidence: 0.6

Marker: Ki-67 - Found 7 UniProt entries
  Top Hit: P46013 | Gene: MKI67 | Protein: Proliferation marker protein Ki-67 | Confidence: 0.6

Marker: TBK1 (pS172) - Found 0 UniProt entries

Marker: TIM-3 - Found 10 UniProt entries
  Top Hit: P35625 | Gene: TIMP3 | Protein: Metalloproteinase inhibitor 3 | Confidence: 0.6

Marker: p60-Src (pY418) - Found 0 UniProt entries

Marker: STAT1 (pY701) - Found 0 UniProt entries

Marker: Desmin - Found 10 UniProt entries
  Top Hit: P17661 | Gene: DES | Protein: Desmin | Confidence: 0.7999999999999999

Marker: hSTING - Found 1 UniProt entries
  Top Hit: Q86WV6 | Gene: STING1 | Protein: Stimulator of interferon genes protein | Confidence: 0.6

Marker: Rb (pS807; pS811) - Found 0 UniProt entries

Marker: Phospho-Tyrosine - Found 10 UniProt entries
  Top Hit: O60729 | Gene: CDC14B | Protein: Dual specificity protein phosphatase CDC14B | Confidence: 0.6

Marker: Ecad - Found 0 UniProt entries

Marker: cPARP - Found 0 UniProt entries

Marker: EGFR - Found 10 UniProt entries

In [ ]:
import json
import os
import concurrent.futures
from tqdm import tqdm
from anthropic import Anthropic, transform_schema
from uniprot_api import lookup_protein # Ensure this is your actual import

# [Paste your Schema and Tool Definitions here from your previous code]
# ... SubcellularLocationEnum, UniprotOutputSchema, tools ...

client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

def curate_single_marker(marker_entry):
    """
    Self-contained function to process one marker.
    Includes the full conversation loop: Ask -> Tool Use -> Tool Result -> Final Answer
    """
    try:
        extracted_marker = marker_entry['extracted_marker']
        marker_type = marker_entry['marker_type']
        row_contents = marker_entry['row_contents']
        
        # 1. Build the prompt
        user_message = f"""Find the correct UniProt entry for this marker:
        **Marker**: {extracted_marker} ({marker_type})
        **Context**: {json.dumps(row_contents, indent=2)}
        
        Search UniProt, review results against metadata (clone, vendor, etc.), and identify the specific target."""

        # 2. First Call: Get Search Intent
        response = client.messages.create(
            model="claude-haiku-4-5",
            max_tokens=1024,
            tools=tools,
            messages=[{"role": "user", "content": user_message}]
        )

        # 3. Handle Tool Use
        if response.stop_reason == "tool_use":
            tool_use = next(block for block in response.content if block.type == "tool_use")
            
            # Run local Python function
            query = tool_use.input["query"]
            organism = tool_use.input.get("organism", "human")
            # print(f"Searching: {query}...") # Optional logging
            
            results = lookup_protein(query, organism)
            
            # Format results for Claude
            # Limit to top 5-10 to save context window
            tool_result_text = f"Found {len(results)} entries. Top results:\n"
            for entry in results[:7]: 
                tool_result_text += (f"- {entry.accession} ({entry.gene_name}): {entry.protein_name}. "
                                     f"Loc: {entry.subcellular_location}. Conf: {entry.confidence_score}\n")

            # 4. Final Call: Get Structured Analysis
            final_response = client.beta.messages.create(
                model="claude-haiku-4-5",
                betas=["structured-outputs-2025-11-13"],
                max_tokens=4096,
                tools=tools,
                messages=[
                    {"role": "user", "content": user_message},
                    {"role": "assistant", "content": response.content}, # Original tool use request
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "tool_result",
                                "tool_use_id": tool_use.id,
                                "content": tool_result_text
                            }
                        ]
                    }
                ],
                output_format={
                    "type": "json_schema",
                    "schema": transform_schema(UniprotOutputSchema)
                }
            )
            
            # Parse the structured output
            structured_data = json.loads(final_response.content[0].text)
            
            # Return combined data
            return {
                **marker_entry,
                "uniprot_data": structured_data,
                "status": "success"
            }
            
        else:
            # Claude didn't search (maybe it knew the answer or refused)
            return {
                **marker_entry,
                "error": "Claude did not trigger a search tool",
                "raw_response": response.content[0].text,
                "status": "no_search"
            }

    except Exception as e:
        return {
            **marker_entry,
            "error": str(e),
            "status": "failed"
        }

def run_concurrent_processing(marker_entries, max_workers=20):
    """
    Process markers in parallel threads.
    """
    results = []
    
    # ThreadPoolExecutor is perfect for I/O bound tasks like API calls
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        # Submit all tasks
        future_to_marker = {executor.submit(curate_single_marker, m): m for m in marker_entries}
        
        # Process as they complete (using tqdm for a progress bar)
        print(f"Processing {len(marker_entries)} markers with {max_workers} threads...")
        for future in tqdm(concurrent.futures.as_completed(future_to_marker), total=len(marker_entries)):
            data = future.result()
            results.append(data)
            
    return results

# --- Execution ---

# 1. Prepare data
# marker_entries = prepare_marker_entries(enhanced_metadata_df_enhanced)

# 2. Run
# For 513 inputs, with 10 workers, this should take about 2-5 minutes total.
# Adjust max_workers based on your Rate Limits (Tier 2/3 accounts can handle 20+)

protein_single_entries = [m for m in marker_entries if m['marker_type'] == 'protein_single']



final_results = run_concurrent_processing(protein_single_entries, max_workers=10)

Processing 490 markers with 10 threads...

 32%|███▏      | 157/490 [01:45<03:44,  1.48it/s]

In [46]:
final_results_df = pd.DataFrame(final_results)
final_results_df.error[0]  # show first 5 errors

NameError: name 'final_results' is not defined

In [ ]:
# One shot with tool use

class MarkerTypeEnum(str, Enum):
    chemical_stain = "chemical_stain"
    blank_or_background = "blank_or_background" 
    protein_group = "protein_group"
    protein_single = "protein_single"
    chemical_element = "chemical_element"
    cd_marker = "cd_marker"
    other_dna = "other_dna"
    other = "other"

class ExtractedlMarkerSchema(BaseModel):
    extracted_marker: str = Field(..., description="The most relevant canonical marker or identifier for the protein, stain or feature being imaged extracted from the metadata row content.")
    marker_type: MarkerTypeEnum = Field(..., description="The type of the canonical marker.")


# make a single request to test
def get_marker_classification(entry):
    prompt = f"""Given the following imaging metadata row content, extract the most relevant canonical marker or identifier and classify its type. If it looks to be 
Metadata Row Content: {json.dumps(entry['row_content'])}
Return the result in JSON format with the fields 'extracted_marker' and 'marker_type'."""
    response = client.beta.messages.create(
        model="claude-haiku-4-5",
        max_tokens=100,
        temperature=0.0,
        betas=["structured-outputs-2025-11-13"],
        messages=[{
            "role": "user",
            "content": prompt
        }],
        output_format={
            "type": "json_schema",
            "schema": transform_schema(ExtractedlMarkerSchema)
        }
    )
    return response.content[0].text

get_marker_classification(metadata_json_small[0])